#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobile
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NewsFactory")]
	public partial class MainDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBlock(Block instance);
    partial void UpdateBlock(Block instance);
    partial void DeleteBlock(Block instance);
    #endregion
		
		public MainDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NewsFactoryConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MainDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MainDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MainDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MainDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vWeb_UsersLoginList> vWeb_UsersLoginLists
		{
			get
			{
				return this.GetTable<vWeb_UsersLoginList>();
			}
		}
		
		public System.Data.Linq.Table<vA_UserRight> vA_UserRights
		{
			get
			{
				return this.GetTable<vA_UserRight>();
			}
		}
		
		public System.Data.Linq.Table<v_ProgramsToList> v_ProgramsToLists
		{
			get
			{
				return this.GetTable<v_ProgramsToList>();
			}
		}
		
		public System.Data.Linq.Table<vLite_NewsToList> vLite_NewsToLists
		{
			get
			{
				return this.GetTable<vLite_NewsToList>();
			}
		}
		
		public System.Data.Linq.Table<vWeb_Block> vWeb_Blocks
		{
			get
			{
				return this.GetTable<vWeb_Block>();
			}
		}
		
		public System.Data.Linq.Table<vWeb_BlockToExtView> vWeb_BlockToExtViews
		{
			get
			{
				return this.GetTable<vWeb_BlockToExtView>();
			}
		}
		
		public System.Data.Linq.Table<Block> Blocks
		{
			get
			{
				return this.GetTable<Block>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vWeb_UsersLoginList")]
	public partial class vWeb_UsersLoginList
	{
		
		private int _ProgramID;
		
		private string _ProgramName;
		
		private bool _Active;
		
		private int _UserID;
		
		private string _UserName;
		
		private string _UserPass;
		
		private int _UserRate;
		
		private System.DateTime _Last_time;
		
		public vWeb_UsersLoginList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramID", DbType="Int NOT NULL")]
		public int ProgramID
		{
			get
			{
				return this._ProgramID;
			}
			set
			{
				if ((this._ProgramID != value))
				{
					this._ProgramID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramName", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ProgramName
		{
			get
			{
				return this._ProgramName;
			}
			set
			{
				if ((this._ProgramName != value))
				{
					this._ProgramName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPass", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string UserPass
		{
			get
			{
				return this._UserPass;
			}
			set
			{
				if ((this._UserPass != value))
				{
					this._UserPass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserRate", DbType="Int NOT NULL")]
		public int UserRate
		{
			get
			{
				return this._UserRate;
			}
			set
			{
				if ((this._UserRate != value))
				{
					this._UserRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_time", DbType="DateTime NOT NULL")]
		public System.DateTime Last_time
		{
			get
			{
				return this._Last_time;
			}
			set
			{
				if ((this._Last_time != value))
				{
					this._Last_time = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vA_UserRights")]
	public partial class vA_UserRight
	{
		
		private int _UserID;
		
		private string _ProgramName;
		
		private string _URightName;
		
		private int _ProgramID;
		
		private int _URightID;
		
		private string _URoleName;
		
		public vA_UserRight()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramName", DbType="NVarChar(255)")]
		public string ProgramName
		{
			get
			{
				return this._ProgramName;
			}
			set
			{
				if ((this._ProgramName != value))
				{
					this._ProgramName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URightName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string URightName
		{
			get
			{
				return this._URightName;
			}
			set
			{
				if ((this._URightName != value))
				{
					this._URightName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramID", DbType="Int NOT NULL")]
		public int ProgramID
		{
			get
			{
				return this._ProgramID;
			}
			set
			{
				if ((this._ProgramID != value))
				{
					this._ProgramID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URightID", DbType="Int NOT NULL")]
		public int URightID
		{
			get
			{
				return this._URightID;
			}
			set
			{
				if ((this._URightID != value))
				{
					this._URightID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URoleName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string URoleName
		{
			get
			{
				return this._URoleName;
			}
			set
			{
				if ((this._URoleName != value))
				{
					this._URoleName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_ProgramsToList")]
	public partial class v_ProgramsToList
	{
		
		private int _id;
		
		private string _Name;
		
		private long _Director;
		
		private bool _Rustv;
		
		private bool _Deleted;
		
		public v_ProgramsToList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Director", DbType="BigInt NOT NULL")]
		public long Director
		{
			get
			{
				return this._Director;
			}
			set
			{
				if ((this._Director != value))
				{
					this._Director = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rustv", DbType="Bit NOT NULL")]
		public bool Rustv
		{
			get
			{
				return this._Rustv;
			}
			set
			{
				if ((this._Rustv != value))
				{
					this._Rustv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit NOT NULL")]
		public bool Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this._Deleted = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vLite_NewsToList")]
	public partial class vLite_NewsToList
	{
		
		private long _id;
		
		private string _Name;
		
		private int _EditorId;
		
		private System.DateTime _NewsDate;
		
		private string _Description;
		
		private long _NewsTime;
		
		private long _CalcTime;
		
		private long _TaskTime;
		
		private int _ProgramId;
		
		private string _Cassete;
		
		private long _Time_Code;
		
		private long _Duration;
		
		public vLite_NewsToList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL")]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditorId", DbType="Int NOT NULL")]
		public int EditorId
		{
			get
			{
				return this._EditorId;
			}
			set
			{
				if ((this._EditorId != value))
				{
					this._EditorId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDate", DbType="DateTime NOT NULL")]
		public System.DateTime NewsDate
		{
			get
			{
				return this._NewsDate;
			}
			set
			{
				if ((this._NewsDate != value))
				{
					this._NewsDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsTime", DbType="BigInt NOT NULL")]
		public long NewsTime
		{
			get
			{
				return this._NewsTime;
			}
			set
			{
				if ((this._NewsTime != value))
				{
					this._NewsTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalcTime", DbType="BigInt NOT NULL")]
		public long CalcTime
		{
			get
			{
				return this._CalcTime;
			}
			set
			{
				if ((this._CalcTime != value))
				{
					this._CalcTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskTime", DbType="BigInt NOT NULL")]
		public long TaskTime
		{
			get
			{
				return this._TaskTime;
			}
			set
			{
				if ((this._TaskTime != value))
				{
					this._TaskTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramId", DbType="Int NOT NULL")]
		public int ProgramId
		{
			get
			{
				return this._ProgramId;
			}
			set
			{
				if ((this._ProgramId != value))
				{
					this._ProgramId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cassete", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Cassete
		{
			get
			{
				return this._Cassete;
			}
			set
			{
				if ((this._Cassete != value))
				{
					this._Cassete = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time_Code", DbType="BigInt NOT NULL")]
		public long Time_Code
		{
			get
			{
				return this._Time_Code;
			}
			set
			{
				if ((this._Time_Code != value))
				{
					this._Time_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duration", DbType="BigInt NOT NULL")]
		public long Duration
		{
			get
			{
				return this._Duration;
			}
			set
			{
				if ((this._Duration != value))
				{
					this._Duration = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vWeb_Blocks")]
	public partial class vWeb_Block
	{
		
		private long _Id;
		
		private string _Name;
		
		private string _TypeName;
		
		private string _BlockTime;
		
		private string _TaskTime;
		
		private string _CalcTime;
		
		private long _NewsId;
		
		private long _ParentId;
		
		private long _CreatorId;
		
		private bool _Ready;
		
		private bool _Approve;
		
		private int _Sort;
		
		private string _LookedUserName;
		
		private string _BgColorIndex;
		
		public vWeb_Block()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeName", DbType="NVarChar(255)")]
		public string TypeName
		{
			get
			{
				return this._TypeName;
			}
			set
			{
				if ((this._TypeName != value))
				{
					this._TypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlockTime", DbType="NVarChar(9)")]
		public string BlockTime
		{
			get
			{
				return this._BlockTime;
			}
			set
			{
				if ((this._BlockTime != value))
				{
					this._BlockTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskTime", DbType="NVarChar(9)")]
		public string TaskTime
		{
			get
			{
				return this._TaskTime;
			}
			set
			{
				if ((this._TaskTime != value))
				{
					this._TaskTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalcTime", DbType="NVarChar(9)")]
		public string CalcTime
		{
			get
			{
				return this._CalcTime;
			}
			set
			{
				if ((this._CalcTime != value))
				{
					this._CalcTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsId", DbType="BigInt NOT NULL")]
		public long NewsId
		{
			get
			{
				return this._NewsId;
			}
			set
			{
				if ((this._NewsId != value))
				{
					this._NewsId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentId", DbType="BigInt NOT NULL")]
		public long ParentId
		{
			get
			{
				return this._ParentId;
			}
			set
			{
				if ((this._ParentId != value))
				{
					this._ParentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatorId", DbType="BigInt NOT NULL")]
		public long CreatorId
		{
			get
			{
				return this._CreatorId;
			}
			set
			{
				if ((this._CreatorId != value))
				{
					this._CreatorId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ready", DbType="Bit NOT NULL")]
		public bool Ready
		{
			get
			{
				return this._Ready;
			}
			set
			{
				if ((this._Ready != value))
				{
					this._Ready = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Approve", DbType="Bit NOT NULL")]
		public bool Approve
		{
			get
			{
				return this._Approve;
			}
			set
			{
				if ((this._Approve != value))
				{
					this._Approve = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sort", DbType="Int NOT NULL")]
		public int Sort
		{
			get
			{
				return this._Sort;
			}
			set
			{
				if ((this._Sort != value))
				{
					this._Sort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LookedUserName", DbType="NVarChar(255)")]
		public string LookedUserName
		{
			get
			{
				return this._LookedUserName;
			}
			set
			{
				if ((this._LookedUserName != value))
				{
					this._LookedUserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BgColorIndex", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string BgColorIndex
		{
			get
			{
				return this._BgColorIndex;
			}
			set
			{
				if ((this._BgColorIndex != value))
				{
					this._BgColorIndex = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vWeb_BlockToExtView")]
	public partial class vWeb_BlockToExtView
	{
		
		private string _Name;
		
		private string _Creator;
		
		private string _Operator;
		
		private string _Jockey;
		
		private string _BlockText;
		
		private string _Description;
		
		private bool _Ready;
		
		private bool _Approve;
		
		private long _Id;
		
		public vWeb_BlockToExtView()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creator", DbType="NVarChar(255)")]
		public string Creator
		{
			get
			{
				return this._Creator;
			}
			set
			{
				if ((this._Creator != value))
				{
					this._Creator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operator", DbType="NVarChar(255)")]
		public string Operator
		{
			get
			{
				return this._Operator;
			}
			set
			{
				if ((this._Operator != value))
				{
					this._Operator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jockey", DbType="NVarChar(255)")]
		public string Jockey
		{
			get
			{
				return this._Jockey;
			}
			set
			{
				if ((this._Jockey != value))
				{
					this._Jockey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlockText", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string BlockText
		{
			get
			{
				return this._BlockText;
			}
			set
			{
				if ((this._BlockText != value))
				{
					this._BlockText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ready", DbType="Bit NOT NULL")]
		public bool Ready
		{
			get
			{
				return this._Ready;
			}
			set
			{
				if ((this._Ready != value))
				{
					this._Ready = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Approve", DbType="Bit NOT NULL")]
		public bool Approve
		{
			get
			{
				return this._Approve;
			}
			set
			{
				if ((this._Approve != value))
				{
					this._Approve = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Blocks")]
	public partial class Block : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Name;
		
		private long _NewsId;
		
		private long _ParentId;
		
		private int _BLockType;
		
		private long _CreatorId;
		
		private long _OperatorId;
		
		private long _JockeyId;
		
		private int _CutterId;
		
		private long _BlockTime;
		
		private long _TaskTime;
		
		private long _CalcTime;
		
		private string _BlockText;
		
		private int _Sort;
		
		private string _Description;
		
		private bool _Ready;
		
		private bool _Approve;
		
		private bool _deleted;
		
		private string _TextLang1;
		
		private string _TextLang2;
		
		private string _TextLang3;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnNewsIdChanging(long value);
    partial void OnNewsIdChanged();
    partial void OnParentIdChanging(long value);
    partial void OnParentIdChanged();
    partial void OnBLockTypeChanging(int value);
    partial void OnBLockTypeChanged();
    partial void OnCreatorIdChanging(long value);
    partial void OnCreatorIdChanged();
    partial void OnOperatorIdChanging(long value);
    partial void OnOperatorIdChanged();
    partial void OnJockeyIdChanging(long value);
    partial void OnJockeyIdChanged();
    partial void OnCutterIdChanging(int value);
    partial void OnCutterIdChanged();
    partial void OnBlockTimeChanging(long value);
    partial void OnBlockTimeChanged();
    partial void OnTaskTimeChanging(long value);
    partial void OnTaskTimeChanged();
    partial void OnCalcTimeChanging(long value);
    partial void OnCalcTimeChanged();
    partial void OnBlockTextChanging(string value);
    partial void OnBlockTextChanged();
    partial void OnSortChanging(int value);
    partial void OnSortChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnReadyChanging(bool value);
    partial void OnReadyChanged();
    partial void OnApproveChanging(bool value);
    partial void OnApproveChanged();
    partial void OndeletedChanging(bool value);
    partial void OndeletedChanged();
    partial void OnTextLang1Changing(string value);
    partial void OnTextLang1Changed();
    partial void OnTextLang2Changing(string value);
    partial void OnTextLang2Changed();
    partial void OnTextLang3Changing(string value);
    partial void OnTextLang3Changed();
    #endregion
		
		public Block()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsId", DbType="BigInt NOT NULL")]
		public long NewsId
		{
			get
			{
				return this._NewsId;
			}
			set
			{
				if ((this._NewsId != value))
				{
					this.OnNewsIdChanging(value);
					this.SendPropertyChanging();
					this._NewsId = value;
					this.SendPropertyChanged("NewsId");
					this.OnNewsIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentId", DbType="BigInt NOT NULL")]
		public long ParentId
		{
			get
			{
				return this._ParentId;
			}
			set
			{
				if ((this._ParentId != value))
				{
					this.OnParentIdChanging(value);
					this.SendPropertyChanging();
					this._ParentId = value;
					this.SendPropertyChanged("ParentId");
					this.OnParentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLockType", DbType="Int NOT NULL")]
		public int BLockType
		{
			get
			{
				return this._BLockType;
			}
			set
			{
				if ((this._BLockType != value))
				{
					this.OnBLockTypeChanging(value);
					this.SendPropertyChanging();
					this._BLockType = value;
					this.SendPropertyChanged("BLockType");
					this.OnBLockTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatorId", DbType="BigInt NOT NULL")]
		public long CreatorId
		{
			get
			{
				return this._CreatorId;
			}
			set
			{
				if ((this._CreatorId != value))
				{
					this.OnCreatorIdChanging(value);
					this.SendPropertyChanging();
					this._CreatorId = value;
					this.SendPropertyChanged("CreatorId");
					this.OnCreatorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatorId", DbType="BigInt NOT NULL")]
		public long OperatorId
		{
			get
			{
				return this._OperatorId;
			}
			set
			{
				if ((this._OperatorId != value))
				{
					this.OnOperatorIdChanging(value);
					this.SendPropertyChanging();
					this._OperatorId = value;
					this.SendPropertyChanged("OperatorId");
					this.OnOperatorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JockeyId", DbType="BigInt NOT NULL")]
		public long JockeyId
		{
			get
			{
				return this._JockeyId;
			}
			set
			{
				if ((this._JockeyId != value))
				{
					this.OnJockeyIdChanging(value);
					this.SendPropertyChanging();
					this._JockeyId = value;
					this.SendPropertyChanged("JockeyId");
					this.OnJockeyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CutterId", DbType="Int NOT NULL")]
		public int CutterId
		{
			get
			{
				return this._CutterId;
			}
			set
			{
				if ((this._CutterId != value))
				{
					this.OnCutterIdChanging(value);
					this.SendPropertyChanging();
					this._CutterId = value;
					this.SendPropertyChanged("CutterId");
					this.OnCutterIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlockTime", DbType="BigInt NOT NULL")]
		public long BlockTime
		{
			get
			{
				return this._BlockTime;
			}
			set
			{
				if ((this._BlockTime != value))
				{
					this.OnBlockTimeChanging(value);
					this.SendPropertyChanging();
					this._BlockTime = value;
					this.SendPropertyChanged("BlockTime");
					this.OnBlockTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskTime", DbType="BigInt NOT NULL")]
		public long TaskTime
		{
			get
			{
				return this._TaskTime;
			}
			set
			{
				if ((this._TaskTime != value))
				{
					this.OnTaskTimeChanging(value);
					this.SendPropertyChanging();
					this._TaskTime = value;
					this.SendPropertyChanged("TaskTime");
					this.OnTaskTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalcTime", DbType="BigInt NOT NULL")]
		public long CalcTime
		{
			get
			{
				return this._CalcTime;
			}
			set
			{
				if ((this._CalcTime != value))
				{
					this.OnCalcTimeChanging(value);
					this.SendPropertyChanging();
					this._CalcTime = value;
					this.SendPropertyChanged("CalcTime");
					this.OnCalcTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlockText", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string BlockText
		{
			get
			{
				return this._BlockText;
			}
			set
			{
				if ((this._BlockText != value))
				{
					this.OnBlockTextChanging(value);
					this.SendPropertyChanging();
					this._BlockText = value;
					this.SendPropertyChanged("BlockText");
					this.OnBlockTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sort", DbType="Int NOT NULL")]
		public int Sort
		{
			get
			{
				return this._Sort;
			}
			set
			{
				if ((this._Sort != value))
				{
					this.OnSortChanging(value);
					this.SendPropertyChanging();
					this._Sort = value;
					this.SendPropertyChanged("Sort");
					this.OnSortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ready", DbType="Bit NOT NULL")]
		public bool Ready
		{
			get
			{
				return this._Ready;
			}
			set
			{
				if ((this._Ready != value))
				{
					this.OnReadyChanging(value);
					this.SendPropertyChanging();
					this._Ready = value;
					this.SendPropertyChanged("Ready");
					this.OnReadyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Approve", DbType="Bit NOT NULL")]
		public bool Approve
		{
			get
			{
				return this._Approve;
			}
			set
			{
				if ((this._Approve != value))
				{
					this.OnApproveChanging(value);
					this.SendPropertyChanging();
					this._Approve = value;
					this.SendPropertyChanged("Approve");
					this.OnApproveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="Bit NOT NULL")]
		public bool deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextLang1", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TextLang1
		{
			get
			{
				return this._TextLang1;
			}
			set
			{
				if ((this._TextLang1 != value))
				{
					this.OnTextLang1Changing(value);
					this.SendPropertyChanging();
					this._TextLang1 = value;
					this.SendPropertyChanged("TextLang1");
					this.OnTextLang1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextLang2", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TextLang2
		{
			get
			{
				return this._TextLang2;
			}
			set
			{
				if ((this._TextLang2 != value))
				{
					this.OnTextLang2Changing(value);
					this.SendPropertyChanging();
					this._TextLang2 = value;
					this.SendPropertyChanged("TextLang2");
					this.OnTextLang2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextLang3", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TextLang3
		{
			get
			{
				return this._TextLang3;
			}
			set
			{
				if ((this._TextLang3 != value))
				{
					this.OnTextLang3Changing(value);
					this.SendPropertyChanging();
					this._TextLang3 = value;
					this.SendPropertyChanged("TextLang3");
					this.OnTextLang3Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
