#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Blocks
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NewsFactory")]
	public partial class DataClassesMediaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InserttWeb_GraphicsLayer(tWeb_GraphicsLayer instance);
    partial void UpdatetWeb_GraphicsLayer(tWeb_GraphicsLayer instance);
    partial void DeletetWeb_GraphicsLayer(tWeb_GraphicsLayer instance);
    partial void InserttWeb_MediaGraphicsItem(tWeb_MediaGraphicsItem instance);
    partial void UpdatetWeb_MediaGraphicsItem(tWeb_MediaGraphicsItem instance);
    partial void DeletetWeb_MediaGraphicsItem(tWeb_MediaGraphicsItem instance);
    partial void InserttWeb_mediaGraphic(tWeb_mediaGraphic instance);
    partial void UpdatetWeb_mediaGraphic(tWeb_mediaGraphic instance);
    partial void DeletetWeb_mediaGraphic(tWeb_mediaGraphic instance);
    #endregion
		
		public DataClassesMediaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NewsFactoryConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesMediaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesMediaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesMediaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesMediaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vWeb_MediaForList> vWeb_MediaForLists
		{
			get
			{
				return this.GetTable<vWeb_MediaForList>();
			}
		}
		
		public System.Data.Linq.Table<vMedia_FileWIthFolderToLIst> vMedia_FileWIthFolderToLIsts
		{
			get
			{
				return this.GetTable<vMedia_FileWIthFolderToLIst>();
			}
		}
		
		public System.Data.Linq.Table<vMedia_ThumbnailsForList> vMedia_ThumbnailsForLists
		{
			get
			{
				return this.GetTable<vMedia_ThumbnailsForList>();
			}
		}
		
		public System.Data.Linq.Table<vMedia_EncoderTask> vMedia_EncoderTasks
		{
			get
			{
				return this.GetTable<vMedia_EncoderTask>();
			}
		}
		
		public System.Data.Linq.Table<vMedia_ListForGenerateLRV> vMedia_ListForGenerateLRVs
		{
			get
			{
				return this.GetTable<vMedia_ListForGenerateLRV>();
			}
		}
		
		public System.Data.Linq.Table<vMedia_ListForGenerateTh> vMedia_ListForGenerateThs
		{
			get
			{
				return this.GetTable<vMedia_ListForGenerateTh>();
			}
		}
		
		public System.Data.Linq.Table<vMedia_ListForGenerateImage> vMedia_ListForGenerateImages
		{
			get
			{
				return this.GetTable<vMedia_ListForGenerateImage>();
			}
		}
		
		public System.Data.Linq.Table<vWeb_ArchiveMediaForList> vWeb_ArchiveMediaForLists
		{
			get
			{
				return this.GetTable<vWeb_ArchiveMediaForList>();
			}
		}
		
		public System.Data.Linq.Table<tWeb_MediaTask> tWeb_MediaTasks
		{
			get
			{
				return this.GetTable<tWeb_MediaTask>();
			}
		}
		
		public System.Data.Linq.Table<tWeb_GraphicsLayer> tWeb_GraphicsLayers
		{
			get
			{
				return this.GetTable<tWeb_GraphicsLayer>();
			}
		}
		
		public System.Data.Linq.Table<tWeb_MediaGraphicsItem> tWeb_MediaGraphicsItems
		{
			get
			{
				return this.GetTable<tWeb_MediaGraphicsItem>();
			}
		}
		
		public System.Data.Linq.Table<tWeb_mediaGraphic> tWeb_mediaGraphics
		{
			get
			{
				return this.GetTable<tWeb_mediaGraphic>();
			}
		}
		
		public System.Data.Linq.Table<vWeb_mobileView> vWeb_mobileView
		{
			get
			{
				return this.GetTable<vWeb_mobileView>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pWeb_ChekUserCookie")]
		public int pWeb_ChekUserCookie([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Coockie", DbType="Int")] System.Nullable<int> coockie)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), coockie);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pMedia_Rename")]
		public int pMedia_Rename([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MediaId", DbType="BigInt")] System.Nullable<long> mediaId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(255)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mediaId, name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pMedia_UpdateSort")]
		public int pMedia_UpdateSort([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MediaId", DbType="BigInt")] System.Nullable<long> mediaId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortOrder", DbType="Int")] System.Nullable<int> sortOrder)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mediaId, sortOrder);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pMedia_UpdateStatus")]
		public int pMedia_UpdateStatus([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MediaId", DbType="BigInt")] System.Nullable<long> mediaId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ready", DbType="Bit")] System.Nullable<bool> ready, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Approve", DbType="Bit")] System.Nullable<bool> approve)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mediaId, ready, approve);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pMedia_Delete")]
		public int pMedia_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MediaId", DbType="BigInt")] System.Nullable<long> mediaId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mediaId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pMedia_FileUploadedAddToBlock")]
		public int pMedia_FileUploadedAddToBlock([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BlockGUID", DbType="NVarChar(1024)")] string blockGUID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FilePath", DbType="NText")] string filePath, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MediaName", DbType="NVarChar(255)")] string mediaName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MediaTypeID", DbType="Int")] System.Nullable<int> mediaTypeID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), blockGUID, filePath, mediaName, mediaTypeID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pMedia_FoldersUpdate")]
		public int pMedia_FoldersUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FolderGuid", DbType="NVarChar(255)")] string folderGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ready", DbType="Bit")] System.Nullable<bool> ready)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), folderGuid, ready);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pMedia_FilesAdd")]
		public int pMedia_FilesAdd([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileGuid", DbType="NVarChar(255)")] string fileGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FolderGuid", DbType="NVarChar(255)")] string folderGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileName", DbType="NVarChar(255)")] string fileName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ready", DbType="Bit")] System.Nullable<bool> ready, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumberInFolder", DbType="Int")] System.Nullable<int> numberInFolder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Size", DbType="BigInt")] System.Nullable<long> size, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string sSourceIp, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="DateTime")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BlockType", DbType="Int")] System.Nullable<int> blockType)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fileGuid, folderGuid, fileName, ready, numberInFolder, size, sSourceIp, startDate, blockType);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pMedia_FoldersAdd")]
		public int pMedia_FoldersAdd([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string sFolderGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bReady, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string sPath, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> iFilesCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sFolderGuid, bReady, sPath, iFilesCount);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pMedia_FilesUpdate")]
		public int pMedia_FilesUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileGuid", DbType="NVarChar(255)")] string fileGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BytesWrite", DbType="BigInt")] System.Nullable<long> bytesWrite, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="DateTime")] System.Nullable<System.DateTime> endDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fileGuid, bytesWrite, endDate);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pMedia_ChunkAdd")]
		public int pMedia_ChunkAdd([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BytesStart", DbType="BigInt")] System.Nullable<long> bytesStart, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BytesEnd", DbType="BigInt")] System.Nullable<long> bytesEnd, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BytesWrite", DbType="BigInt")] System.Nullable<long> bytesWrite, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileGuid", DbType="NVarChar(255)")] string fileGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bytesStart, bytesEnd, bytesWrite, fileGuid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pMedia_EncoderSetTaskActive")]
		public int pMedia_EncoderSetTaskActive([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TaskId", DbType="Int")] System.Nullable<int> taskId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EncoderGuid", DbType="NVarChar(255)")] string encoderGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), taskId, encoderGuid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pMedia_FilesLrvUpdate")]
		public int pMedia_FilesLrvUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EncoderGuid", DbType="NVarChar(255)")] string encoderGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LrvFileName", DbType="NVarChar(255)")] string lrvFileName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LrvFilePath", DbType="NVarChar(255)")] string lrvFilePath, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LrvStatus", DbType="Bit")] System.Nullable<bool> lrvStatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EncoderIsActive", DbType="Bit")] System.Nullable<bool> encoderIsActive)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), encoderGuid, lrvFileName, lrvFilePath, lrvStatus, encoderIsActive);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pMedia_EncoderSetTaskDisActive")]
		public int pMedia_EncoderSetTaskDisActive([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EncoderGuid", DbType="NVarChar(255)")] string encoderGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), encoderGuid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pMedia_EncoderSetTaskError")]
		public int pMedia_EncoderSetTaskError([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EncoderGuid", DbType="NVarChar(255)")] string encoderGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), encoderGuid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pMedia_ThumbnailInsertFromImage")]
		public int pMedia_ThumbnailInsertFromImage([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileGuid", DbType="NVarChar(255)")] string fileGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Img", DbType="Image")] System.Data.Linq.Binary img, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Th1", DbType="Image")] System.Data.Linq.Binary th1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Image")] System.Data.Linq.Binary th2)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fileGuid, img, th1, th2);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pMedia_ThumbnailInsert")]
		public int pMedia_ThumbnailInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EncoderGuid", DbType="NVarChar(255)")] string encoderGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Img", DbType="Image")] System.Data.Linq.Binary img, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> number, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Th1", DbType="Image")] System.Data.Linq.Binary th1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Th2", DbType="Image")] System.Data.Linq.Binary th2)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), encoderGuid, img, number, th1, th2);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pMedia_AddLRV")]
		public int pMedia_AddLRV([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Int")] System.Nullable<int> status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Path", DbType="NText")] string path, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Message", DbType="NVarChar(255)")] string message)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, status, path, message);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pMedia_AddImage")]
		public int pMedia_AddImage([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Int")] System.Nullable<int> status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Path", DbType="NText")] string path, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Message", DbType="NVarChar(255)")] string message)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, status, path, message);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pMedia_AddImage")]
		public int pMedia_AddImage1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Int")] System.Nullable<int> status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Path", DbType="NText")] string path, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Message", DbType="NVarChar(255)")] string message)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, status, path, message);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pMedia_SortAlphablet")]
		public int pMedia_SortAlphablet([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> parentId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parentId);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vWeb_MediaForList")]
	public partial class vWeb_MediaForList
	{
		
		private long _Id;
		
		private string _Name;
		
		private int _BLockType;
		
		private long _CreatorId;
		
		private long _OperatorId;
		
		private long _JockeyId;
		
		private long _BlockTime;
		
		private long _TaskTime;
		
		private long _CalcTime;
		
		private string _BlockText;
		
		private bool _Ready;
		
		private bool _Approve;
		
		private string _TextLang1;
		
		private string _TextLang2;
		
		private string _TextLang3;
		
		private long _ParentId;
		
		private int _Sort;
		
		private string _Description;
		
		public vWeb_MediaForList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLockType", DbType="Int NOT NULL")]
		public int BLockType
		{
			get
			{
				return this._BLockType;
			}
			set
			{
				if ((this._BLockType != value))
				{
					this._BLockType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatorId", DbType="BigInt NOT NULL")]
		public long CreatorId
		{
			get
			{
				return this._CreatorId;
			}
			set
			{
				if ((this._CreatorId != value))
				{
					this._CreatorId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatorId", DbType="BigInt NOT NULL")]
		public long OperatorId
		{
			get
			{
				return this._OperatorId;
			}
			set
			{
				if ((this._OperatorId != value))
				{
					this._OperatorId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JockeyId", DbType="BigInt NOT NULL")]
		public long JockeyId
		{
			get
			{
				return this._JockeyId;
			}
			set
			{
				if ((this._JockeyId != value))
				{
					this._JockeyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlockTime", DbType="BigInt NOT NULL")]
		public long BlockTime
		{
			get
			{
				return this._BlockTime;
			}
			set
			{
				if ((this._BlockTime != value))
				{
					this._BlockTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskTime", DbType="BigInt NOT NULL")]
		public long TaskTime
		{
			get
			{
				return this._TaskTime;
			}
			set
			{
				if ((this._TaskTime != value))
				{
					this._TaskTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalcTime", DbType="BigInt NOT NULL")]
		public long CalcTime
		{
			get
			{
				return this._CalcTime;
			}
			set
			{
				if ((this._CalcTime != value))
				{
					this._CalcTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlockText", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string BlockText
		{
			get
			{
				return this._BlockText;
			}
			set
			{
				if ((this._BlockText != value))
				{
					this._BlockText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ready", DbType="Bit NOT NULL")]
		public bool Ready
		{
			get
			{
				return this._Ready;
			}
			set
			{
				if ((this._Ready != value))
				{
					this._Ready = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Approve", DbType="Bit NOT NULL")]
		public bool Approve
		{
			get
			{
				return this._Approve;
			}
			set
			{
				if ((this._Approve != value))
				{
					this._Approve = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextLang1", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TextLang1
		{
			get
			{
				return this._TextLang1;
			}
			set
			{
				if ((this._TextLang1 != value))
				{
					this._TextLang1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextLang2", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TextLang2
		{
			get
			{
				return this._TextLang2;
			}
			set
			{
				if ((this._TextLang2 != value))
				{
					this._TextLang2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextLang3", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TextLang3
		{
			get
			{
				return this._TextLang3;
			}
			set
			{
				if ((this._TextLang3 != value))
				{
					this._TextLang3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentId", DbType="BigInt NOT NULL")]
		public long ParentId
		{
			get
			{
				return this._ParentId;
			}
			set
			{
				if ((this._ParentId != value))
				{
					this._ParentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sort", DbType="Int NOT NULL")]
		public int Sort
		{
			get
			{
				return this._Sort;
			}
			set
			{
				if ((this._Sort != value))
				{
					this._Sort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vMedia_FileWIthFolderToLIst")]
	public partial class vMedia_FileWIthFolderToLIst
	{
		
		private string _FolderGuid;
		
		private long _FolderId;
		
		private string _FolderREady;
		
		private bool _Ready;
		
		private string _FolderPAth;
		
		private int _FileCountInFOlder;
		
		private long _FIleId;
		
		private string _FileGuid;
		
		private string _FileName;
		
		private System.Nullable<bool> _FIleREady;
		
		private System.Nullable<int> _NumberInFolder;
		
		private System.Nullable<long> _FileSize;
		
		private string _sSourceIp;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private System.Nullable<int> _BlockType;
		
		public vMedia_FileWIthFolderToLIst()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FolderGuid", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string FolderGuid
		{
			get
			{
				return this._FolderGuid;
			}
			set
			{
				if ((this._FolderGuid != value))
				{
					this._FolderGuid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FolderId", DbType="BigInt NOT NULL")]
		public long FolderId
		{
			get
			{
				return this._FolderId;
			}
			set
			{
				if ((this._FolderId != value))
				{
					this._FolderId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FolderREady", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string FolderREady
		{
			get
			{
				return this._FolderREady;
			}
			set
			{
				if ((this._FolderREady != value))
				{
					this._FolderREady = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ready", DbType="Bit NOT NULL")]
		public bool Ready
		{
			get
			{
				return this._Ready;
			}
			set
			{
				if ((this._Ready != value))
				{
					this._Ready = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FolderPAth", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string FolderPAth
		{
			get
			{
				return this._FolderPAth;
			}
			set
			{
				if ((this._FolderPAth != value))
				{
					this._FolderPAth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileCountInFOlder", DbType="Int NOT NULL")]
		public int FileCountInFOlder
		{
			get
			{
				return this._FileCountInFOlder;
			}
			set
			{
				if ((this._FileCountInFOlder != value))
				{
					this._FileCountInFOlder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIleId", DbType="BigInt NOT NULL")]
		public long FIleId
		{
			get
			{
				return this._FIleId;
			}
			set
			{
				if ((this._FIleId != value))
				{
					this._FIleId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileGuid", DbType="NVarChar(255)")]
		public string FileGuid
		{
			get
			{
				return this._FileGuid;
			}
			set
			{
				if ((this._FileGuid != value))
				{
					this._FileGuid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(255)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIleREady", DbType="Bit")]
		public System.Nullable<bool> FIleREady
		{
			get
			{
				return this._FIleREady;
			}
			set
			{
				if ((this._FIleREady != value))
				{
					this._FIleREady = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberInFolder", DbType="Int")]
		public System.Nullable<int> NumberInFolder
		{
			get
			{
				return this._NumberInFolder;
			}
			set
			{
				if ((this._NumberInFolder != value))
				{
					this._NumberInFolder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileSize", DbType="BigInt")]
		public System.Nullable<long> FileSize
		{
			get
			{
				return this._FileSize;
			}
			set
			{
				if ((this._FileSize != value))
				{
					this._FileSize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sSourceIp", DbType="NVarChar(255)")]
		public string sSourceIp
		{
			get
			{
				return this._sSourceIp;
			}
			set
			{
				if ((this._sSourceIp != value))
				{
					this._sSourceIp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this._StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this._EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlockType", DbType="Int")]
		public System.Nullable<int> BlockType
		{
			get
			{
				return this._BlockType;
			}
			set
			{
				if ((this._BlockType != value))
				{
					this._BlockType = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vMedia_ThumbnailsForList")]
	public partial class vMedia_ThumbnailsForList
	{
		
		private int _id;
		
		private System.DateTime _DateAdd;
		
		private int _Number;
		
		private System.Data.Linq.Binary _image;
		
		private string _FileGuid;
		
		public vMedia_ThumbnailsForList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAdd", DbType="DateTime NOT NULL")]
		public System.DateTime DateAdd
		{
			get
			{
				return this._DateAdd;
			}
			set
			{
				if ((this._DateAdd != value))
				{
					this._DateAdd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="Int NOT NULL")]
		public int Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this._Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this._image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileGuid", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string FileGuid
		{
			get
			{
				return this._FileGuid;
			}
			set
			{
				if ((this._FileGuid != value))
				{
					this._FileGuid = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vMedia_EncoderTask")]
	public partial class vMedia_EncoderTask
	{
		
		private long _id;
		
		private string _EncoderGuid;
		
		private System.Nullable<System.DateTime> _DateLastStart;
		
		private bool _IsActive;
		
		private int _ErrorCount;
		
		private bool _IsComplite;
		
		private string _FileGuid;
		
		private string _FileName;
		
		private string _LRVFileName;
		
		private string _LRVPath;
		
		public vMedia_EncoderTask()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL")]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EncoderGuid", DbType="NVarChar(255)")]
		public string EncoderGuid
		{
			get
			{
				return this._EncoderGuid;
			}
			set
			{
				if ((this._EncoderGuid != value))
				{
					this._EncoderGuid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateLastStart", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateLastStart
		{
			get
			{
				return this._DateLastStart;
			}
			set
			{
				if ((this._DateLastStart != value))
				{
					this._DateLastStart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorCount", DbType="Int NOT NULL")]
		public int ErrorCount
		{
			get
			{
				return this._ErrorCount;
			}
			set
			{
				if ((this._ErrorCount != value))
				{
					this._ErrorCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsComplite", DbType="Bit NOT NULL")]
		public bool IsComplite
		{
			get
			{
				return this._IsComplite;
			}
			set
			{
				if ((this._IsComplite != value))
				{
					this._IsComplite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileGuid", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string FileGuid
		{
			get
			{
				return this._FileGuid;
			}
			set
			{
				if ((this._FileGuid != value))
				{
					this._FileGuid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(255)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LRVFileName", DbType="NVarChar(255)")]
		public string LRVFileName
		{
			get
			{
				return this._LRVFileName;
			}
			set
			{
				if ((this._LRVFileName != value))
				{
					this._LRVFileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LRVPath", DbType="NVarChar(255)")]
		public string LRVPath
		{
			get
			{
				return this._LRVPath;
			}
			set
			{
				if ((this._LRVPath != value))
				{
					this._LRVPath = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vMedia_ListForGenerateLRV")]
	public partial class vMedia_ListForGenerateLRV
	{
		
		private int _id;
		
		private string _PicSource;
		
		public vMedia_ListForGenerateLRV()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicSource", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string PicSource
		{
			get
			{
				return this._PicSource;
			}
			set
			{
				if ((this._PicSource != value))
				{
					this._PicSource = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vMedia_ListForGenerateTh")]
	public partial class vMedia_ListForGenerateTh
	{
		
		private int _id;
		
		private string _PicSource;
		
		public vMedia_ListForGenerateTh()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicSource", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string PicSource
		{
			get
			{
				return this._PicSource;
			}
			set
			{
				if ((this._PicSource != value))
				{
					this._PicSource = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vMedia_ListForGenerateImages")]
	public partial class vMedia_ListForGenerateImage
	{
		
		private int _id;
		
		private string _PicSource;
		
		public vMedia_ListForGenerateImage()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicSource", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string PicSource
		{
			get
			{
				return this._PicSource;
			}
			set
			{
				if ((this._PicSource != value))
				{
					this._PicSource = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vWeb_ArchiveMediaForList")]
	public partial class vWeb_ArchiveMediaForList
	{
		
		private long _Id;
		
		private string _Name;
		
		private int _BLockType;
		
		private int _CreatorId;
		
		private int _OperatorId;
		
		private int _JockeyId;
		
		private int _BlockTime;
		
		private int _TaskTime;
		
		private int _CalcTime;
		
		private string _BlockText;
		
		private bool _Ready;
		
		private bool _Approve;
		
		private string _TextLang1;
		
		private string _TextLang2;
		
		private string _TextLang3;
		
		private long _ParentId;
		
		private int _Sort;
		
		private string _Description;
		
		public vWeb_ArchiveMediaForList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLockType", DbType="Int NOT NULL")]
		public int BLockType
		{
			get
			{
				return this._BLockType;
			}
			set
			{
				if ((this._BLockType != value))
				{
					this._BLockType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatorId", DbType="Int NOT NULL")]
		public int CreatorId
		{
			get
			{
				return this._CreatorId;
			}
			set
			{
				if ((this._CreatorId != value))
				{
					this._CreatorId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatorId", DbType="Int NOT NULL")]
		public int OperatorId
		{
			get
			{
				return this._OperatorId;
			}
			set
			{
				if ((this._OperatorId != value))
				{
					this._OperatorId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JockeyId", DbType="Int NOT NULL")]
		public int JockeyId
		{
			get
			{
				return this._JockeyId;
			}
			set
			{
				if ((this._JockeyId != value))
				{
					this._JockeyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlockTime", DbType="Int NOT NULL")]
		public int BlockTime
		{
			get
			{
				return this._BlockTime;
			}
			set
			{
				if ((this._BlockTime != value))
				{
					this._BlockTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskTime", DbType="Int NOT NULL")]
		public int TaskTime
		{
			get
			{
				return this._TaskTime;
			}
			set
			{
				if ((this._TaskTime != value))
				{
					this._TaskTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalcTime", DbType="Int NOT NULL")]
		public int CalcTime
		{
			get
			{
				return this._CalcTime;
			}
			set
			{
				if ((this._CalcTime != value))
				{
					this._CalcTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlockText", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string BlockText
		{
			get
			{
				return this._BlockText;
			}
			set
			{
				if ((this._BlockText != value))
				{
					this._BlockText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ready", DbType="Bit NOT NULL")]
		public bool Ready
		{
			get
			{
				return this._Ready;
			}
			set
			{
				if ((this._Ready != value))
				{
					this._Ready = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Approve", DbType="Bit NOT NULL")]
		public bool Approve
		{
			get
			{
				return this._Approve;
			}
			set
			{
				if ((this._Approve != value))
				{
					this._Approve = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextLang1", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TextLang1
		{
			get
			{
				return this._TextLang1;
			}
			set
			{
				if ((this._TextLang1 != value))
				{
					this._TextLang1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextLang2", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TextLang2
		{
			get
			{
				return this._TextLang2;
			}
			set
			{
				if ((this._TextLang2 != value))
				{
					this._TextLang2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextLang3", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TextLang3
		{
			get
			{
				return this._TextLang3;
			}
			set
			{
				if ((this._TextLang3 != value))
				{
					this._TextLang3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentId", DbType="BigInt NOT NULL")]
		public long ParentId
		{
			get
			{
				return this._ParentId;
			}
			set
			{
				if ((this._ParentId != value))
				{
					this._ParentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sort", DbType="Int NOT NULL")]
		public int Sort
		{
			get
			{
				return this._Sort;
			}
			set
			{
				if ((this._Sort != value))
				{
					this._Sort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tWeb_MediaTask")]
	public partial class tWeb_MediaTask
	{
		
		private int _id;
		
		private long _MediaId;
		
		private System.Nullable<System.DateTime> _DateAdd;
		
		private System.Nullable<System.DateTime> _DateAddComplite;
		
		private int _LRVStatus;
		
		private int _LRVCount;
		
		private string _LRVMessage;
		
		private System.DateTime _LRVLastDate;
		
		private int _PICStatus;
		
		private int _PICCount;
		
		private string _PICMessage;
		
		private System.Nullable<System.DateTime> _PICLastDate;
		
		private bool _isComplite;
		
		public tWeb_MediaTask()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MediaId", DbType="BigInt NOT NULL")]
		public long MediaId
		{
			get
			{
				return this._MediaId;
			}
			set
			{
				if ((this._MediaId != value))
				{
					this._MediaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAdd", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateAdd
		{
			get
			{
				return this._DateAdd;
			}
			set
			{
				if ((this._DateAdd != value))
				{
					this._DateAdd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAddComplite", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateAddComplite
		{
			get
			{
				return this._DateAddComplite;
			}
			set
			{
				if ((this._DateAddComplite != value))
				{
					this._DateAddComplite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LRVStatus", DbType="Int NOT NULL")]
		public int LRVStatus
		{
			get
			{
				return this._LRVStatus;
			}
			set
			{
				if ((this._LRVStatus != value))
				{
					this._LRVStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LRVCount", DbType="Int NOT NULL")]
		public int LRVCount
		{
			get
			{
				return this._LRVCount;
			}
			set
			{
				if ((this._LRVCount != value))
				{
					this._LRVCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LRVMessage", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string LRVMessage
		{
			get
			{
				return this._LRVMessage;
			}
			set
			{
				if ((this._LRVMessage != value))
				{
					this._LRVMessage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LRVLastDate", DbType="DateTime NOT NULL")]
		public System.DateTime LRVLastDate
		{
			get
			{
				return this._LRVLastDate;
			}
			set
			{
				if ((this._LRVLastDate != value))
				{
					this._LRVLastDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PICStatus", DbType="Int NOT NULL")]
		public int PICStatus
		{
			get
			{
				return this._PICStatus;
			}
			set
			{
				if ((this._PICStatus != value))
				{
					this._PICStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PICCount", DbType="Int NOT NULL")]
		public int PICCount
		{
			get
			{
				return this._PICCount;
			}
			set
			{
				if ((this._PICCount != value))
				{
					this._PICCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PICMessage", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string PICMessage
		{
			get
			{
				return this._PICMessage;
			}
			set
			{
				if ((this._PICMessage != value))
				{
					this._PICMessage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PICLastDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PICLastDate
		{
			get
			{
				return this._PICLastDate;
			}
			set
			{
				if ((this._PICLastDate != value))
				{
					this._PICLastDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isComplite", DbType="Bit NOT NULL")]
		public bool isComplite
		{
			get
			{
				return this._isComplite;
			}
			set
			{
				if ((this._isComplite != value))
				{
					this._isComplite = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tWeb_GraphicsLayers")]
	public partial class tWeb_GraphicsLayer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _title;
		
		private bool _deleted;
		
		private System.DateTime _dateCreation;
		
		private EntitySet<tWeb_mediaGraphic> _tWeb_mediaGraphics;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndeletedChanging(bool value);
    partial void OndeletedChanged();
    partial void OndateCreationChanging(System.DateTime value);
    partial void OndateCreationChanged();
    #endregion
		
		public tWeb_GraphicsLayer()
		{
			this._tWeb_mediaGraphics = new EntitySet<tWeb_mediaGraphic>(new Action<tWeb_mediaGraphic>(this.attach_tWeb_mediaGraphics), new Action<tWeb_mediaGraphic>(this.detach_tWeb_mediaGraphics));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="Bit NOT NULL")]
		public bool deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateCreation", DbType="DateTime NOT NULL")]
		public System.DateTime dateCreation
		{
			get
			{
				return this._dateCreation;
			}
			set
			{
				if ((this._dateCreation != value))
				{
					this.OndateCreationChanging(value);
					this.SendPropertyChanging();
					this._dateCreation = value;
					this.SendPropertyChanged("dateCreation");
					this.OndateCreationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tWeb_GraphicsLayer_tWeb_mediaGraphic", Storage="_tWeb_mediaGraphics", ThisKey="id", OtherKey="layerId")]
		internal EntitySet<tWeb_mediaGraphic> tWeb_mediaGraphics
		{
			get
			{
				return this._tWeb_mediaGraphics;
			}
			set
			{
				this._tWeb_mediaGraphics.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tWeb_mediaGraphics(tWeb_mediaGraphic entity)
		{
			this.SendPropertyChanging();
			entity.tWeb_GraphicsLayer = this;
		}
		
		private void detach_tWeb_mediaGraphics(tWeb_mediaGraphic entity)
		{
			this.SendPropertyChanging();
			entity.tWeb_GraphicsLayer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tWeb_MediaGraphicsItems")]
	public partial class tWeb_MediaGraphicsItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _mediaGraphicsId;
		
		private double _timeInSec;
		
		private string _text;
		
		private EntityRef<tWeb_mediaGraphic> _tWeb_mediaGraphic;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnmediaGraphicsIdChanging(string value);
    partial void OnmediaGraphicsIdChanged();
    partial void OntimeInSecChanging(double value);
    partial void OntimeInSecChanged();
    partial void OntextChanging(string value);
    partial void OntextChanged();
    #endregion
		
		public tWeb_MediaGraphicsItem()
		{
			this._tWeb_mediaGraphic = default(EntityRef<tWeb_mediaGraphic>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(90) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mediaGraphicsId", DbType="NVarChar(90) NOT NULL", CanBeNull=false)]
		public string mediaGraphicsId
		{
			get
			{
				return this._mediaGraphicsId;
			}
			set
			{
				if ((this._mediaGraphicsId != value))
				{
					if (this._tWeb_mediaGraphic.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmediaGraphicsIdChanging(value);
					this.SendPropertyChanging();
					this._mediaGraphicsId = value;
					this.SendPropertyChanged("mediaGraphicsId");
					this.OnmediaGraphicsIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeInSec", DbType="Float NOT NULL")]
		public double timeInSec
		{
			get
			{
				return this._timeInSec;
			}
			set
			{
				if ((this._timeInSec != value))
				{
					this.OntimeInSecChanging(value);
					this.SendPropertyChanging();
					this._timeInSec = value;
					this.SendPropertyChanged("timeInSec");
					this.OntimeInSecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this.OntextChanging(value);
					this.SendPropertyChanging();
					this._text = value;
					this.SendPropertyChanged("text");
					this.OntextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tWeb_mediaGraphic_tWeb_MediaGraphicsItem", Storage="_tWeb_mediaGraphic", ThisKey="mediaGraphicsId", OtherKey="id", IsForeignKey=true)]
		internal tWeb_mediaGraphic tWeb_mediaGraphic
		{
			get
			{
				return this._tWeb_mediaGraphic.Entity;
			}
			set
			{
				tWeb_mediaGraphic previousValue = this._tWeb_mediaGraphic.Entity;
				if (((previousValue != value) 
							|| (this._tWeb_mediaGraphic.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tWeb_mediaGraphic.Entity = null;
						previousValue.tWeb_MediaGraphicsItems.Remove(this);
					}
					this._tWeb_mediaGraphic.Entity = value;
					if ((value != null))
					{
						value.tWeb_MediaGraphicsItems.Add(this);
						this._mediaGraphicsId = value.id;
					}
					else
					{
						this._mediaGraphicsId = default(string);
					}
					this.SendPropertyChanged("tWeb_mediaGraphic");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tWeb_mediaGraphic")]
	public partial class tWeb_mediaGraphic : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private int _layerId;
		
		private long _MediaId;
		
		private EntitySet<tWeb_MediaGraphicsItem> _tWeb_MediaGraphicsItems;
		
		private EntityRef<tWeb_GraphicsLayer> _tWeb_GraphicsLayer;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnlayerIdChanging(int value);
    partial void OnlayerIdChanged();
    partial void OnMediaIdChanging(long value);
    partial void OnMediaIdChanged();
    #endregion
		
		public tWeb_mediaGraphic()
		{
			this._tWeb_MediaGraphicsItems = new EntitySet<tWeb_MediaGraphicsItem>(new Action<tWeb_MediaGraphicsItem>(this.attach_tWeb_MediaGraphicsItems), new Action<tWeb_MediaGraphicsItem>(this.detach_tWeb_MediaGraphicsItems));
			this._tWeb_GraphicsLayer = default(EntityRef<tWeb_GraphicsLayer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(90) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_layerId", DbType="Int NOT NULL")]
		public int layerId
		{
			get
			{
				return this._layerId;
			}
			set
			{
				if ((this._layerId != value))
				{
					if (this._tWeb_GraphicsLayer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnlayerIdChanging(value);
					this.SendPropertyChanging();
					this._layerId = value;
					this.SendPropertyChanged("layerId");
					this.OnlayerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MediaId", DbType="BigInt NOT NULL")]
		public long MediaId
		{
			get
			{
				return this._MediaId;
			}
			set
			{
				if ((this._MediaId != value))
				{
					this.OnMediaIdChanging(value);
					this.SendPropertyChanging();
					this._MediaId = value;
					this.SendPropertyChanged("MediaId");
					this.OnMediaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tWeb_mediaGraphic_tWeb_MediaGraphicsItem", Storage="_tWeb_MediaGraphicsItems", ThisKey="id", OtherKey="mediaGraphicsId")]
		internal EntitySet<tWeb_MediaGraphicsItem> tWeb_MediaGraphicsItems
		{
			get
			{
				return this._tWeb_MediaGraphicsItems;
			}
			set
			{
				this._tWeb_MediaGraphicsItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tWeb_GraphicsLayer_tWeb_mediaGraphic", Storage="_tWeb_GraphicsLayer", ThisKey="layerId", OtherKey="id", IsForeignKey=true)]
		internal tWeb_GraphicsLayer tWeb_GraphicsLayer
		{
			get
			{
				return this._tWeb_GraphicsLayer.Entity;
			}
			set
			{
				tWeb_GraphicsLayer previousValue = this._tWeb_GraphicsLayer.Entity;
				if (((previousValue != value) 
							|| (this._tWeb_GraphicsLayer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tWeb_GraphicsLayer.Entity = null;
						previousValue.tWeb_mediaGraphics.Remove(this);
					}
					this._tWeb_GraphicsLayer.Entity = value;
					if ((value != null))
					{
						value.tWeb_mediaGraphics.Add(this);
						this._layerId = value.id;
					}
					else
					{
						this._layerId = default(int);
					}
					this.SendPropertyChanged("tWeb_GraphicsLayer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tWeb_MediaGraphicsItems(tWeb_MediaGraphicsItem entity)
		{
			this.SendPropertyChanging();
			entity.tWeb_mediaGraphic = this;
		}
		
		private void detach_tWeb_MediaGraphicsItems(tWeb_MediaGraphicsItem entity)
		{
			this.SendPropertyChanging();
			entity.tWeb_mediaGraphic = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vWeb_mobileView")]
	public partial class vWeb_mobileView
	{
		
		private string _id;
		
		private System.DateTime _insertDate;
		
		private string _message;
		
		private string _imgFile;
		
		public vWeb_mobileView()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(90) NOT NULL", CanBeNull=false)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insertDate", DbType="DateTime NOT NULL")]
		public System.DateTime insertDate
		{
			get
			{
				return this._insertDate;
			}
			set
			{
				if ((this._insertDate != value))
				{
					this._insertDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_message", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string message
		{
			get
			{
				return this._message;
			}
			set
			{
				if ((this._message != value))
				{
					this._message = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgFile", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string imgFile
		{
			get
			{
				return this._imgFile;
			}
			set
			{
				if ((this._imgFile != value))
				{
					this._imgFile = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
