#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.News
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NewsFactory")]
	public partial class NewsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertProgram(Program instance);
    partial void UpdateProgram(Program instance);
    partial void DeleteProgram(Program instance);
    partial void InsertNew(New instance);
    partial void UpdateNew(New instance);
    partial void DeleteNew(New instance);
    partial void InsertCopyNew(CopyNew instance);
    partial void UpdateCopyNew(CopyNew instance);
    partial void DeleteCopyNew(CopyNew instance);
    partial void InserttWeb_RssSource(tWeb_RssSource instance);
    partial void UpdatetWeb_RssSource(tWeb_RssSource instance);
    partial void DeletetWeb_RssSource(tWeb_RssSource instance);
    partial void InsertURole(URole instance);
    partial void UpdateURole(URole instance);
    partial void DeleteURole(URole instance);
    partial void InsertURightsToRole(URightsToRole instance);
    partial void UpdateURightsToRole(URightsToRole instance);
    partial void DeleteURightsToRole(URightsToRole instance);
    partial void InsertURight(URight instance);
    partial void UpdateURight(URight instance);
    partial void DeleteURight(URight instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertUUserToProgram(UUserToProgram instance);
    partial void UpdateUUserToProgram(UUserToProgram instance);
    partial void DeleteUUserToProgram(UUserToProgram instance);
    #endregion
		
		public NewsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NewsFactoryConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NewsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NewsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NewsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NewsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Program> Programs
		{
			get
			{
				return this.GetTable<Program>();
			}
		}
		
		public System.Data.Linq.Table<New> News
		{
			get
			{
				return this.GetTable<New>();
			}
		}
		
		public System.Data.Linq.Table<vWeb_ProgramsFromCookie> vWeb_ProgramsFromCookies
		{
			get
			{
				return this.GetTable<vWeb_ProgramsFromCookie>();
			}
		}
		
		public System.Data.Linq.Table<CopyNew> CopyNews
		{
			get
			{
				return this.GetTable<CopyNew>();
			}
		}
		
		public System.Data.Linq.Table<vUsersRight> vUsersRights
		{
			get
			{
				return this.GetTable<vUsersRight>();
			}
		}
		
		public System.Data.Linq.Table<tWeb_RssSource> tWeb_RssSources
		{
			get
			{
				return this.GetTable<tWeb_RssSource>();
			}
		}
		
		public System.Data.Linq.Table<vWeb_UsertForMessager> vWeb_UsertForMessagers
		{
			get
			{
				return this.GetTable<vWeb_UsertForMessager>();
			}
		}
		
		public System.Data.Linq.Table<vWeb_User> vWeb_Users
		{
			get
			{
				return this.GetTable<vWeb_User>();
			}
		}
		
		public System.Data.Linq.Table<vWeb_RssFeed> vWeb_RssFeeds
		{
			get
			{
				return this.GetTable<vWeb_RssFeed>();
			}
		}
		
		public System.Data.Linq.Table<vUsersProgramList> vUsersProgramLists
		{
			get
			{
				return this.GetTable<vUsersProgramList>();
			}
		}
		
		public System.Data.Linq.Table<URole> URoles
		{
			get
			{
				return this.GetTable<URole>();
			}
		}
		
		public System.Data.Linq.Table<URightsToRole> URightsToRoles
		{
			get
			{
				return this.GetTable<URightsToRole>();
			}
		}
		
		public System.Data.Linq.Table<URight> URights
		{
			get
			{
				return this.GetTable<URight>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<UUserToProgram> UUserToPrograms
		{
			get
			{
				return this.GetTable<UUserToProgram>();
			}
		}
		
		public System.Data.Linq.Table<vBlock> vBlocks
		{
			get
			{
				return this.GetTable<vBlock>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fWeb_GetUserIdFromCoockie", IsComposable=true)]
		public System.Nullable<int> fWeb_GetUserIdFromCoockie([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cookie", DbType="Int")] System.Nullable<int> cookie)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cookie).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fWeb_GetUserIdFromCoockie", IsComposable=true)]
		public System.Nullable<int> fWeb_GetUserIdFromCoockie1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cookie", DbType="Int")] System.Nullable<int> cookie)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cookie).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_NewsToCopybox")]
		public int sp_NewsToCopybox([global::System.Data.Linq.Mapping.ParameterAttribute(Name="News_id", DbType="BigInt")] System.Nullable<long> news_id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GroupId", DbType="BigInt")] System.Nullable<long> groupId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="BigInt")] System.Nullable<long> userId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), news_id, groupId, userId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_NewsFromCopyboxTemplate")]
		public int sp_NewsFromCopyboxTemplate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="News_Id", DbType="BigInt")] System.Nullable<long> news_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EditorId", DbType="Int")] System.Nullable<int> editorId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProgramId", DbType="Int")] System.Nullable<int> programId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), news_Id, editorId, programId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pWeb_NewNews")]
		public int pWeb_NewNews([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> programId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), programId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pWeb_ChekUserCookie")]
		public int pWeb_ChekUserCookie([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Coockie", DbType="Int")] System.Nullable<int> coockie)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), coockie);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fWeb_NewsWithBlocksToXML", IsComposable=true)]
		public System.Xml.Linq.XElement fWeb_NewsWithBlocksToXML()
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fWeb_CheckUserRightForShowMessager", IsComposable=true)]
		public System.Nullable<bool> fWeb_CheckUserRightForShowMessager([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Userid", DbType="Int")] System.Nullable<int> userid)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_NewsToArchive")]
		public ISingleResult<sp_NewsToArchiveResult> sp_NewsToArchive([global::System.Data.Linq.Mapping.ParameterAttribute(Name="News_id", DbType="BigInt")] System.Nullable<long> news_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), news_id);
			return ((ISingleResult<sp_NewsToArchiveResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ArchiveToNews")]
		public int sp_ArchiveToNews([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pWeb_InsertRssToNews")]
		public int pWeb_InsertRssToNews([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MessageId", DbType="Int")] System.Nullable<int> messageId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewsId", DbType="BigInt")] System.Nullable<long> newsId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatorId", DbType="Int")] System.Nullable<int> creatorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), messageId, newsId, creatorId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pWeb_InsertRssFeed")]
		public int pWeb_InsertRssFeed([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Date", DbType="DateTime")] System.Nullable<System.DateTime> date, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ImgLink", DbType="NVarChar(255)")] string imgLink, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(255)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lid", DbType="NText")] string lid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Link", DbType="NVarChar(255)")] string link, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Guid", DbType="NVarChar(255)")] string guid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SourceId", DbType="Int")] System.Nullable<int> sourceId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), date, imgLink, name, lid, link, guid, sourceId);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Programs")]
	public partial class Program : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Name;
		
		private long _Director;
		
		private bool _Rustv;
		
		private bool _Deleted;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDirectorChanging(long value);
    partial void OnDirectorChanged();
    partial void OnRustvChanging(bool value);
    partial void OnRustvChanged();
    partial void OnDeletedChanging(bool value);
    partial void OnDeletedChanged();
    #endregion
		
		public Program()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Director", DbType="BigInt NOT NULL")]
		public long Director
		{
			get
			{
				return this._Director;
			}
			set
			{
				if ((this._Director != value))
				{
					this.OnDirectorChanging(value);
					this.SendPropertyChanging();
					this._Director = value;
					this.SendPropertyChanged("Director");
					this.OnDirectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rustv", DbType="Bit NOT NULL")]
		public bool Rustv
		{
			get
			{
				return this._Rustv;
			}
			set
			{
				if ((this._Rustv != value))
				{
					this.OnRustvChanging(value);
					this.SendPropertyChanging();
					this._Rustv = value;
					this.SendPropertyChanged("Rustv");
					this.OnRustvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit NOT NULL")]
		public bool Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.News")]
	public partial class New : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _Name;
		
		private int _EditorId;
		
		private System.DateTime _NewsDate;
		
		private string _Description;
		
		private long _NewsTime;
		
		private long _CalcTime;
		
		private long _TaskTime;
		
		private bool _Deleted;
		
		private int _ProgramId;
		
		private string _Cassete;
		
		private long _Time_Code;
		
		private long _Duration;
		
		private EntityRef<Program> _Program;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEditorIdChanging(int value);
    partial void OnEditorIdChanged();
    partial void OnNewsDateChanging(System.DateTime value);
    partial void OnNewsDateChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnNewsTimeChanging(long value);
    partial void OnNewsTimeChanged();
    partial void OnCalcTimeChanging(long value);
    partial void OnCalcTimeChanged();
    partial void OnTaskTimeChanging(long value);
    partial void OnTaskTimeChanged();
    partial void OnDeletedChanging(bool value);
    partial void OnDeletedChanged();
    partial void OnProgramIdChanging(int value);
    partial void OnProgramIdChanged();
    partial void OnCasseteChanging(string value);
    partial void OnCasseteChanged();
    partial void OnTime_CodeChanging(long value);
    partial void OnTime_CodeChanged();
    partial void OnDurationChanging(long value);
    partial void OnDurationChanged();
    #endregion
		
		public New()
		{
			this._Program = default(EntityRef<Program>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditorId", DbType="Int NOT NULL")]
		public int EditorId
		{
			get
			{
				return this._EditorId;
			}
			set
			{
				if ((this._EditorId != value))
				{
					this.OnEditorIdChanging(value);
					this.SendPropertyChanging();
					this._EditorId = value;
					this.SendPropertyChanged("EditorId");
					this.OnEditorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDate", DbType="DateTime NOT NULL")]
		public System.DateTime NewsDate
		{
			get
			{
				return this._NewsDate;
			}
			set
			{
				if ((this._NewsDate != value))
				{
					this.OnNewsDateChanging(value);
					this.SendPropertyChanging();
					this._NewsDate = value;
					this.SendPropertyChanged("NewsDate");
					this.OnNewsDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsTime", DbType="BigInt NOT NULL")]
		public long NewsTime
		{
			get
			{
				return this._NewsTime;
			}
			set
			{
				if ((this._NewsTime != value))
				{
					this.OnNewsTimeChanging(value);
					this.SendPropertyChanging();
					this._NewsTime = value;
					this.SendPropertyChanged("NewsTime");
					this.OnNewsTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalcTime", DbType="BigInt NOT NULL")]
		public long CalcTime
		{
			get
			{
				return this._CalcTime;
			}
			set
			{
				if ((this._CalcTime != value))
				{
					this.OnCalcTimeChanging(value);
					this.SendPropertyChanging();
					this._CalcTime = value;
					this.SendPropertyChanged("CalcTime");
					this.OnCalcTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskTime", DbType="BigInt NOT NULL")]
		public long TaskTime
		{
			get
			{
				return this._TaskTime;
			}
			set
			{
				if ((this._TaskTime != value))
				{
					this.OnTaskTimeChanging(value);
					this.SendPropertyChanging();
					this._TaskTime = value;
					this.SendPropertyChanged("TaskTime");
					this.OnTaskTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit NOT NULL")]
		public bool Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramId", DbType="Int NOT NULL")]
		public int ProgramId
		{
			get
			{
				return this._ProgramId;
			}
			set
			{
				if ((this._ProgramId != value))
				{
					if (this._Program.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProgramIdChanging(value);
					this.SendPropertyChanging();
					this._ProgramId = value;
					this.SendPropertyChanged("ProgramId");
					this.OnProgramIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cassete", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Cassete
		{
			get
			{
				return this._Cassete;
			}
			set
			{
				if ((this._Cassete != value))
				{
					this.OnCasseteChanging(value);
					this.SendPropertyChanging();
					this._Cassete = value;
					this.SendPropertyChanged("Cassete");
					this.OnCasseteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time_Code", DbType="BigInt NOT NULL")]
		public long Time_Code
		{
			get
			{
				return this._Time_Code;
			}
			set
			{
				if ((this._Time_Code != value))
				{
					this.OnTime_CodeChanging(value);
					this.SendPropertyChanging();
					this._Time_Code = value;
					this.SendPropertyChanged("Time_Code");
					this.OnTime_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duration", DbType="BigInt NOT NULL")]
		public long Duration
		{
			get
			{
				return this._Duration;
			}
			set
			{
				if ((this._Duration != value))
				{
					this.OnDurationChanging(value);
					this.SendPropertyChanging();
					this._Duration = value;
					this.SendPropertyChanged("Duration");
					this.OnDurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Program_New", Storage="_Program", ThisKey="ProgramId", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Program Program
		{
			get
			{
				return this._Program.Entity;
			}
			set
			{
				if ((this._Program.Entity != value))
				{
					this.SendPropertyChanging();
					this._Program.Entity = value;
					this.SendPropertyChanged("Program");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vWeb_ProgramsFromCookie")]
	public partial class vWeb_ProgramsFromCookie
	{
		
		private int _ProgramID;
		
		private string _UserName;
		
		private int _UserID;
		
		private int _Cookie;
		
		private string _Name;
		
		public vWeb_ProgramsFromCookie()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramID", DbType="Int NOT NULL")]
		public int ProgramID
		{
			get
			{
				return this._ProgramID;
			}
			set
			{
				if ((this._ProgramID != value))
				{
					this._ProgramID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cookie", DbType="Int NOT NULL")]
		public int Cookie
		{
			get
			{
				return this._Cookie;
			}
			set
			{
				if ((this._Cookie != value))
				{
					this._Cookie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CopyNews")]
	public partial class CopyNew : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _Name;
		
		private int _EditorId;
		
		private System.DateTime _NewsDate;
		
		private string _Description;
		
		private long _NewsTime;
		
		private long _CalcTime;
		
		private long _TaskTime;
		
		private bool _Deleted;
		
		private long _ProgramId;
		
		private long _GroupID;
		
		private string _Cassete;
		
		private long _Time_Code;
		
		private long _Duration;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEditorIdChanging(int value);
    partial void OnEditorIdChanged();
    partial void OnNewsDateChanging(System.DateTime value);
    partial void OnNewsDateChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnNewsTimeChanging(long value);
    partial void OnNewsTimeChanged();
    partial void OnCalcTimeChanging(long value);
    partial void OnCalcTimeChanged();
    partial void OnTaskTimeChanging(long value);
    partial void OnTaskTimeChanged();
    partial void OnDeletedChanging(bool value);
    partial void OnDeletedChanged();
    partial void OnProgramIdChanging(long value);
    partial void OnProgramIdChanged();
    partial void OnGroupIDChanging(long value);
    partial void OnGroupIDChanged();
    partial void OnCasseteChanging(string value);
    partial void OnCasseteChanged();
    partial void OnTime_CodeChanging(long value);
    partial void OnTime_CodeChanged();
    partial void OnDurationChanging(long value);
    partial void OnDurationChanged();
    #endregion
		
		public CopyNew()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditorId", DbType="Int NOT NULL")]
		public int EditorId
		{
			get
			{
				return this._EditorId;
			}
			set
			{
				if ((this._EditorId != value))
				{
					this.OnEditorIdChanging(value);
					this.SendPropertyChanging();
					this._EditorId = value;
					this.SendPropertyChanged("EditorId");
					this.OnEditorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDate", DbType="DateTime NOT NULL")]
		public System.DateTime NewsDate
		{
			get
			{
				return this._NewsDate;
			}
			set
			{
				if ((this._NewsDate != value))
				{
					this.OnNewsDateChanging(value);
					this.SendPropertyChanging();
					this._NewsDate = value;
					this.SendPropertyChanged("NewsDate");
					this.OnNewsDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsTime", DbType="BigInt NOT NULL")]
		public long NewsTime
		{
			get
			{
				return this._NewsTime;
			}
			set
			{
				if ((this._NewsTime != value))
				{
					this.OnNewsTimeChanging(value);
					this.SendPropertyChanging();
					this._NewsTime = value;
					this.SendPropertyChanged("NewsTime");
					this.OnNewsTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalcTime", DbType="BigInt NOT NULL")]
		public long CalcTime
		{
			get
			{
				return this._CalcTime;
			}
			set
			{
				if ((this._CalcTime != value))
				{
					this.OnCalcTimeChanging(value);
					this.SendPropertyChanging();
					this._CalcTime = value;
					this.SendPropertyChanged("CalcTime");
					this.OnCalcTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskTime", DbType="BigInt NOT NULL")]
		public long TaskTime
		{
			get
			{
				return this._TaskTime;
			}
			set
			{
				if ((this._TaskTime != value))
				{
					this.OnTaskTimeChanging(value);
					this.SendPropertyChanging();
					this._TaskTime = value;
					this.SendPropertyChanged("TaskTime");
					this.OnTaskTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit NOT NULL")]
		public bool Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramId", DbType="BigInt NOT NULL")]
		public long ProgramId
		{
			get
			{
				return this._ProgramId;
			}
			set
			{
				if ((this._ProgramId != value))
				{
					this.OnProgramIdChanging(value);
					this.SendPropertyChanging();
					this._ProgramId = value;
					this.SendPropertyChanged("ProgramId");
					this.OnProgramIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupID", DbType="BigInt NOT NULL")]
		public long GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					this.OnGroupIDChanging(value);
					this.SendPropertyChanging();
					this._GroupID = value;
					this.SendPropertyChanged("GroupID");
					this.OnGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cassete", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Cassete
		{
			get
			{
				return this._Cassete;
			}
			set
			{
				if ((this._Cassete != value))
				{
					this.OnCasseteChanging(value);
					this.SendPropertyChanging();
					this._Cassete = value;
					this.SendPropertyChanged("Cassete");
					this.OnCasseteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time_Code", DbType="BigInt NOT NULL")]
		public long Time_Code
		{
			get
			{
				return this._Time_Code;
			}
			set
			{
				if ((this._Time_Code != value))
				{
					this.OnTime_CodeChanging(value);
					this.SendPropertyChanging();
					this._Time_Code = value;
					this.SendPropertyChanged("Time_Code");
					this.OnTime_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duration", DbType="BigInt NOT NULL")]
		public long Duration
		{
			get
			{
				return this._Duration;
			}
			set
			{
				if ((this._Duration != value))
				{
					this.OnDurationChanging(value);
					this.SendPropertyChanging();
					this._Duration = value;
					this.SendPropertyChanged("Duration");
					this.OnDurationChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vUsersRights")]
	public partial class vUsersRight
	{
		
		private int _ProgramID;
		
		private string _ProgramName;
		
		private int _RightID;
		
		private int _UserID;
		
		private string _UserPass;
		
		private int _UserRate;
		
		private string _UserName;
		
		public vUsersRight()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramID", DbType="Int NOT NULL")]
		public int ProgramID
		{
			get
			{
				return this._ProgramID;
			}
			set
			{
				if ((this._ProgramID != value))
				{
					this._ProgramID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramName", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ProgramName
		{
			get
			{
				return this._ProgramName;
			}
			set
			{
				if ((this._ProgramName != value))
				{
					this._ProgramName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RightID", DbType="Int NOT NULL")]
		public int RightID
		{
			get
			{
				return this._RightID;
			}
			set
			{
				if ((this._RightID != value))
				{
					this._RightID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPass", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string UserPass
		{
			get
			{
				return this._UserPass;
			}
			set
			{
				if ((this._UserPass != value))
				{
					this._UserPass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserRate", DbType="Int NOT NULL")]
		public int UserRate
		{
			get
			{
				return this._UserRate;
			}
			set
			{
				if ((this._UserRate != value))
				{
					this._UserRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tWeb_RssSources")]
	public partial class tWeb_RssSource : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Name;
		
		private string _URL;
		
		private bool _Active;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnURLChanging(string value);
    partial void OnURLChanged();
    partial void OnActiveChanging(bool value);
    partial void OnActiveChanged();
    #endregion
		
		public tWeb_RssSource()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="NVarChar(255)")]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this.OnURLChanging(value);
					this.SendPropertyChanging();
					this._URL = value;
					this.SendPropertyChanged("URL");
					this.OnURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vWeb_UsertForMessager")]
	public partial class vWeb_UsertForMessager
	{
		
		private int _UserID;
		
		private string _UserName;
		
		private bool _Active;
		
		public vWeb_UsertForMessager()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vWeb_Users")]
	public partial class vWeb_User
	{
		
		private int _UserID;
		
		private string _UserName;
		
		private bool _Active;
		
		public vWeb_User()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vWeb_RssFeed")]
	public partial class vWeb_RssFeed
	{
		
		private int _id;
		
		private System.Nullable<long> _exsternalId;
		
		private string _Name;
		
		private string _Lid;
		
		private System.Nullable<System.DateTime> _Date;
		
		private int _SourceId;
		
		private string _Link;
		
		private string _ImgLink;
		
		private string _GUID;
		
		private string _Expr1;
		
		private bool _Active;
		
		public vWeb_RssFeed()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exsternalId", DbType="BigInt")]
		public System.Nullable<long> exsternalId
		{
			get
			{
				return this._exsternalId;
			}
			set
			{
				if ((this._exsternalId != value))
				{
					this._exsternalId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lid", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Lid
		{
			get
			{
				return this._Lid;
			}
			set
			{
				if ((this._Lid != value))
				{
					this._Lid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceId", DbType="Int NOT NULL")]
		public int SourceId
		{
			get
			{
				return this._SourceId;
			}
			set
			{
				if ((this._SourceId != value))
				{
					this._SourceId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="NVarChar(255)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this._Link = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImgLink", DbType="NVarChar(255)")]
		public string ImgLink
		{
			get
			{
				return this._ImgLink;
			}
			set
			{
				if ((this._ImgLink != value))
				{
					this._ImgLink = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID", DbType="NVarChar(255)")]
		public string GUID
		{
			get
			{
				return this._GUID;
			}
			set
			{
				if ((this._GUID != value))
				{
					this._GUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expr1", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Expr1
		{
			get
			{
				return this._Expr1;
			}
			set
			{
				if ((this._Expr1 != value))
				{
					this._Expr1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vUsersProgramList")]
	public partial class vUsersProgramList
	{
		
		private int _ProgramID;
		
		private string _ProgramName;
		
		private bool _RightID;
		
		private int _UserID;
		
		private string _UserName;
		
		private bool _UserPass;
		
		private int _UserRate;
		
		public vUsersProgramList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramID", DbType="Int NOT NULL")]
		public int ProgramID
		{
			get
			{
				return this._ProgramID;
			}
			set
			{
				if ((this._ProgramID != value))
				{
					this._ProgramID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramName", DbType="NVarChar(255)")]
		public string ProgramName
		{
			get
			{
				return this._ProgramName;
			}
			set
			{
				if ((this._ProgramName != value))
				{
					this._ProgramName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RightID", DbType="Bit NOT NULL")]
		public bool RightID
		{
			get
			{
				return this._RightID;
			}
			set
			{
				if ((this._RightID != value))
				{
					this._RightID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPass", DbType="Bit NOT NULL")]
		public bool UserPass
		{
			get
			{
				return this._UserPass;
			}
			set
			{
				if ((this._UserPass != value))
				{
					this._UserPass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserRate", DbType="Int NOT NULL")]
		public int UserRate
		{
			get
			{
				return this._UserRate;
			}
			set
			{
				if ((this._UserRate != value))
				{
					this._UserRate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.URoles")]
	public partial class URole : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _URoleID;
		
		private string _URoleName;
		
		private string _URoleDescription;
		
		private bool _URoleProgDepend;
		
		private bool _URoleUndelete;
		
		private System.Nullable<short> _URoleGroup;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnURoleIDChanging(int value);
    partial void OnURoleIDChanged();
    partial void OnURoleNameChanging(string value);
    partial void OnURoleNameChanged();
    partial void OnURoleDescriptionChanging(string value);
    partial void OnURoleDescriptionChanged();
    partial void OnURoleProgDependChanging(bool value);
    partial void OnURoleProgDependChanged();
    partial void OnURoleUndeleteChanging(bool value);
    partial void OnURoleUndeleteChanged();
    partial void OnURoleGroupChanging(System.Nullable<short> value);
    partial void OnURoleGroupChanged();
    #endregion
		
		public URole()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URoleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int URoleID
		{
			get
			{
				return this._URoleID;
			}
			set
			{
				if ((this._URoleID != value))
				{
					this.OnURoleIDChanging(value);
					this.SendPropertyChanging();
					this._URoleID = value;
					this.SendPropertyChanged("URoleID");
					this.OnURoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URoleName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string URoleName
		{
			get
			{
				return this._URoleName;
			}
			set
			{
				if ((this._URoleName != value))
				{
					this.OnURoleNameChanging(value);
					this.SendPropertyChanging();
					this._URoleName = value;
					this.SendPropertyChanged("URoleName");
					this.OnURoleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URoleDescription", DbType="NVarChar(255)")]
		public string URoleDescription
		{
			get
			{
				return this._URoleDescription;
			}
			set
			{
				if ((this._URoleDescription != value))
				{
					this.OnURoleDescriptionChanging(value);
					this.SendPropertyChanging();
					this._URoleDescription = value;
					this.SendPropertyChanged("URoleDescription");
					this.OnURoleDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URoleProgDepend", DbType="Bit NOT NULL")]
		public bool URoleProgDepend
		{
			get
			{
				return this._URoleProgDepend;
			}
			set
			{
				if ((this._URoleProgDepend != value))
				{
					this.OnURoleProgDependChanging(value);
					this.SendPropertyChanging();
					this._URoleProgDepend = value;
					this.SendPropertyChanged("URoleProgDepend");
					this.OnURoleProgDependChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URoleUndelete", DbType="Bit NOT NULL")]
		public bool URoleUndelete
		{
			get
			{
				return this._URoleUndelete;
			}
			set
			{
				if ((this._URoleUndelete != value))
				{
					this.OnURoleUndeleteChanging(value);
					this.SendPropertyChanging();
					this._URoleUndelete = value;
					this.SendPropertyChanged("URoleUndelete");
					this.OnURoleUndeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URoleGroup", DbType="SmallInt")]
		public System.Nullable<short> URoleGroup
		{
			get
			{
				return this._URoleGroup;
			}
			set
			{
				if ((this._URoleGroup != value))
				{
					this.OnURoleGroupChanging(value);
					this.SendPropertyChanging();
					this._URoleGroup = value;
					this.SendPropertyChanged("URoleGroup");
					this.OnURoleGroupChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.URightsToRole")]
	public partial class URightsToRole : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _URoleID;
		
		private int _URightID;
		
		private EntityRef<URole> _URole;
		
		private EntityRef<URight> _URight;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnURoleIDChanging(int value);
    partial void OnURoleIDChanged();
    partial void OnURightIDChanging(int value);
    partial void OnURightIDChanged();
    #endregion
		
		public URightsToRole()
		{
			this._URole = default(EntityRef<URole>);
			this._URight = default(EntityRef<URight>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URoleID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int URoleID
		{
			get
			{
				return this._URoleID;
			}
			set
			{
				if ((this._URoleID != value))
				{
					if (this._URole.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnURoleIDChanging(value);
					this.SendPropertyChanging();
					this._URoleID = value;
					this.SendPropertyChanged("URoleID");
					this.OnURoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URightID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int URightID
		{
			get
			{
				return this._URightID;
			}
			set
			{
				if ((this._URightID != value))
				{
					if (this._URight.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnURightIDChanging(value);
					this.SendPropertyChanging();
					this._URightID = value;
					this.SendPropertyChanged("URightID");
					this.OnURightIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="URole_URightsToRole", Storage="_URole", ThisKey="URoleID", OtherKey="URoleID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public URole URole
		{
			get
			{
				return this._URole.Entity;
			}
			set
			{
				if ((this._URole.Entity != value))
				{
					this.SendPropertyChanging();
					this._URole.Entity = value;
					this.SendPropertyChanged("URole");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="URight_URightsToRole", Storage="_URight", ThisKey="URightID", OtherKey="URightID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public URight URight
		{
			get
			{
				return this._URight.Entity;
			}
			set
			{
				if ((this._URight.Entity != value))
				{
					this.SendPropertyChanging();
					this._URight.Entity = value;
					this.SendPropertyChanged("URight");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.URights")]
	public partial class URight : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _URightID;
		
		private string _URightName;
		
		private string _URightGroupName;
		
		private bool _URightProgDepend;
		
		private System.Nullable<int> _URightGroup;
		
		private string _URightDescription;
		
		private bool _URightCh;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnURightIDChanging(int value);
    partial void OnURightIDChanged();
    partial void OnURightNameChanging(string value);
    partial void OnURightNameChanged();
    partial void OnURightGroupNameChanging(string value);
    partial void OnURightGroupNameChanged();
    partial void OnURightProgDependChanging(bool value);
    partial void OnURightProgDependChanged();
    partial void OnURightGroupChanging(System.Nullable<int> value);
    partial void OnURightGroupChanged();
    partial void OnURightDescriptionChanging(string value);
    partial void OnURightDescriptionChanged();
    partial void OnURightChChanging(bool value);
    partial void OnURightChChanged();
    #endregion
		
		public URight()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URightID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int URightID
		{
			get
			{
				return this._URightID;
			}
			set
			{
				if ((this._URightID != value))
				{
					this.OnURightIDChanging(value);
					this.SendPropertyChanging();
					this._URightID = value;
					this.SendPropertyChanged("URightID");
					this.OnURightIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URightName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string URightName
		{
			get
			{
				return this._URightName;
			}
			set
			{
				if ((this._URightName != value))
				{
					this.OnURightNameChanging(value);
					this.SendPropertyChanging();
					this._URightName = value;
					this.SendPropertyChanged("URightName");
					this.OnURightNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URightGroupName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string URightGroupName
		{
			get
			{
				return this._URightGroupName;
			}
			set
			{
				if ((this._URightGroupName != value))
				{
					this.OnURightGroupNameChanging(value);
					this.SendPropertyChanging();
					this._URightGroupName = value;
					this.SendPropertyChanged("URightGroupName");
					this.OnURightGroupNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URightProgDepend", DbType="Bit NOT NULL")]
		public bool URightProgDepend
		{
			get
			{
				return this._URightProgDepend;
			}
			set
			{
				if ((this._URightProgDepend != value))
				{
					this.OnURightProgDependChanging(value);
					this.SendPropertyChanging();
					this._URightProgDepend = value;
					this.SendPropertyChanged("URightProgDepend");
					this.OnURightProgDependChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URightGroup", DbType="Int")]
		public System.Nullable<int> URightGroup
		{
			get
			{
				return this._URightGroup;
			}
			set
			{
				if ((this._URightGroup != value))
				{
					this.OnURightGroupChanging(value);
					this.SendPropertyChanging();
					this._URightGroup = value;
					this.SendPropertyChanged("URightGroup");
					this.OnURightGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URightDescription", DbType="NVarChar(255)")]
		public string URightDescription
		{
			get
			{
				return this._URightDescription;
			}
			set
			{
				if ((this._URightDescription != value))
				{
					this.OnURightDescriptionChanging(value);
					this.SendPropertyChanging();
					this._URightDescription = value;
					this.SendPropertyChanged("URightDescription");
					this.OnURightDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URightCh", DbType="Bit NOT NULL")]
		public bool URightCh
		{
			get
			{
				return this._URightCh;
			}
			set
			{
				if ((this._URightCh != value))
				{
					this.OnURightChChanging(value);
					this.SendPropertyChanging();
					this._URightCh = value;
					this.SendPropertyChanged("URightCh");
					this.OnURightChChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _UserName;
		
		private string _pass;
		
		private bool _Active;
		
		private System.DateTime _Last_time;
		
		private int _ReadRate;
		
		private bool _deleted;
		
		private int _PrintTemplateId;
		
		private int _BlockTypeId;
		
		private int _AbrigeBlockTypeId;
		
		private bool _OnlyMy;
		
		private bool _Enter;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnpassChanging(string value);
    partial void OnpassChanged();
    partial void OnActiveChanging(bool value);
    partial void OnActiveChanged();
    partial void OnLast_timeChanging(System.DateTime value);
    partial void OnLast_timeChanged();
    partial void OnReadRateChanging(int value);
    partial void OnReadRateChanged();
    partial void OndeletedChanging(bool value);
    partial void OndeletedChanged();
    partial void OnPrintTemplateIdChanging(int value);
    partial void OnPrintTemplateIdChanged();
    partial void OnBlockTypeIdChanging(int value);
    partial void OnBlockTypeIdChanged();
    partial void OnAbrigeBlockTypeIdChanging(int value);
    partial void OnAbrigeBlockTypeIdChanged();
    partial void OnOnlyMyChanging(bool value);
    partial void OnOnlyMyChanged();
    partial void OnEnterChanging(bool value);
    partial void OnEnterChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_time", DbType="DateTime NOT NULL")]
		public System.DateTime Last_time
		{
			get
			{
				return this._Last_time;
			}
			set
			{
				if ((this._Last_time != value))
				{
					this.OnLast_timeChanging(value);
					this.SendPropertyChanging();
					this._Last_time = value;
					this.SendPropertyChanged("Last_time");
					this.OnLast_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReadRate", DbType="Int NOT NULL")]
		public int ReadRate
		{
			get
			{
				return this._ReadRate;
			}
			set
			{
				if ((this._ReadRate != value))
				{
					this.OnReadRateChanging(value);
					this.SendPropertyChanging();
					this._ReadRate = value;
					this.SendPropertyChanged("ReadRate");
					this.OnReadRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="Bit NOT NULL")]
		public bool deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintTemplateId", DbType="Int NOT NULL")]
		public int PrintTemplateId
		{
			get
			{
				return this._PrintTemplateId;
			}
			set
			{
				if ((this._PrintTemplateId != value))
				{
					this.OnPrintTemplateIdChanging(value);
					this.SendPropertyChanging();
					this._PrintTemplateId = value;
					this.SendPropertyChanged("PrintTemplateId");
					this.OnPrintTemplateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlockTypeId", DbType="Int NOT NULL")]
		public int BlockTypeId
		{
			get
			{
				return this._BlockTypeId;
			}
			set
			{
				if ((this._BlockTypeId != value))
				{
					this.OnBlockTypeIdChanging(value);
					this.SendPropertyChanging();
					this._BlockTypeId = value;
					this.SendPropertyChanged("BlockTypeId");
					this.OnBlockTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AbrigeBlockTypeId", DbType="Int NOT NULL")]
		public int AbrigeBlockTypeId
		{
			get
			{
				return this._AbrigeBlockTypeId;
			}
			set
			{
				if ((this._AbrigeBlockTypeId != value))
				{
					this.OnAbrigeBlockTypeIdChanging(value);
					this.SendPropertyChanging();
					this._AbrigeBlockTypeId = value;
					this.SendPropertyChanged("AbrigeBlockTypeId");
					this.OnAbrigeBlockTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnlyMy", DbType="Bit NOT NULL")]
		public bool OnlyMy
		{
			get
			{
				return this._OnlyMy;
			}
			set
			{
				if ((this._OnlyMy != value))
				{
					this.OnOnlyMyChanging(value);
					this.SendPropertyChanging();
					this._OnlyMy = value;
					this.SendPropertyChanged("OnlyMy");
					this.OnOnlyMyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enter", DbType="Bit NOT NULL")]
		public bool Enter
		{
			get
			{
				return this._Enter;
			}
			set
			{
				if ((this._Enter != value))
				{
					this.OnEnterChanging(value);
					this.SendPropertyChanging();
					this._Enter = value;
					this.SendPropertyChanged("Enter");
					this.OnEnterChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UUserToProgram")]
	public partial class UUserToProgram : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UUserToProgramID;
		
		private int _UserID;
		
		private int _ProgramID;
		
		private int _URoleID;
		
		private EntityRef<Program> _Program;
		
		private EntityRef<URole> _URole;
		
		private EntityRef<User> _User;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUUserToProgramIDChanging(int value);
    partial void OnUUserToProgramIDChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnProgramIDChanging(int value);
    partial void OnProgramIDChanged();
    partial void OnURoleIDChanging(int value);
    partial void OnURoleIDChanged();
    #endregion
		
		public UUserToProgram()
		{
			this._Program = default(EntityRef<Program>);
			this._URole = default(EntityRef<URole>);
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UUserToProgramID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UUserToProgramID
		{
			get
			{
				return this._UUserToProgramID;
			}
			set
			{
				if ((this._UUserToProgramID != value))
				{
					this.OnUUserToProgramIDChanging(value);
					this.SendPropertyChanging();
					this._UUserToProgramID = value;
					this.SendPropertyChanged("UUserToProgramID");
					this.OnUUserToProgramIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramID", DbType="Int NOT NULL")]
		public int ProgramID
		{
			get
			{
				return this._ProgramID;
			}
			set
			{
				if ((this._ProgramID != value))
				{
					if (this._Program.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProgramIDChanging(value);
					this.SendPropertyChanging();
					this._ProgramID = value;
					this.SendPropertyChanged("ProgramID");
					this.OnProgramIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URoleID", DbType="Int NOT NULL")]
		public int URoleID
		{
			get
			{
				return this._URoleID;
			}
			set
			{
				if ((this._URoleID != value))
				{
					if (this._URole.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnURoleIDChanging(value);
					this.SendPropertyChanging();
					this._URoleID = value;
					this.SendPropertyChanged("URoleID");
					this.OnURoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Program_UUserToProgram", Storage="_Program", ThisKey="ProgramID", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Program Program
		{
			get
			{
				return this._Program.Entity;
			}
			set
			{
				if ((this._Program.Entity != value))
				{
					this.SendPropertyChanging();
					this._Program.Entity = value;
					this.SendPropertyChanged("Program");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="URole_UUserToProgram", Storage="_URole", ThisKey="URoleID", OtherKey="URoleID", IsForeignKey=true)]
		public URole URole
		{
			get
			{
				return this._URole.Entity;
			}
			set
			{
				if ((this._URole.Entity != value))
				{
					this.SendPropertyChanging();
					this._URole.Entity = value;
					this.SendPropertyChanged("URole");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_UUserToProgram", Storage="_User", ThisKey="UserID", OtherKey="UserID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				if ((this._User.Entity != value))
				{
					this.SendPropertyChanging();
					this._User.Entity = value;
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vBlocks")]
	public partial class vBlock
	{
		
		private long _Id;
		
		private string _Name;
		
		private string _TypeName;
		
		private string _BlockTime;
		
		private string _TaskTime;
		
		private string _CalcTime;
		
		private long _NewsId;
		
		private long _ParentId;
		
		private long _CreatorId;
		
		private bool _Ready;
		
		private bool _Approve;
		
		private int _Sort;
		
		private long _OperatorId;
		
		private long _JockeyId;
		
		private int _CutterId;
		
		public vBlock()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeName", DbType="NVarChar(255)")]
		public string TypeName
		{
			get
			{
				return this._TypeName;
			}
			set
			{
				if ((this._TypeName != value))
				{
					this._TypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlockTime", DbType="NVarChar(9)")]
		public string BlockTime
		{
			get
			{
				return this._BlockTime;
			}
			set
			{
				if ((this._BlockTime != value))
				{
					this._BlockTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskTime", DbType="NVarChar(9)")]
		public string TaskTime
		{
			get
			{
				return this._TaskTime;
			}
			set
			{
				if ((this._TaskTime != value))
				{
					this._TaskTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalcTime", DbType="NVarChar(9)")]
		public string CalcTime
		{
			get
			{
				return this._CalcTime;
			}
			set
			{
				if ((this._CalcTime != value))
				{
					this._CalcTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsId", DbType="BigInt NOT NULL")]
		public long NewsId
		{
			get
			{
				return this._NewsId;
			}
			set
			{
				if ((this._NewsId != value))
				{
					this._NewsId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentId", DbType="BigInt NOT NULL")]
		public long ParentId
		{
			get
			{
				return this._ParentId;
			}
			set
			{
				if ((this._ParentId != value))
				{
					this._ParentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatorId", DbType="BigInt NOT NULL")]
		public long CreatorId
		{
			get
			{
				return this._CreatorId;
			}
			set
			{
				if ((this._CreatorId != value))
				{
					this._CreatorId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ready", DbType="Bit NOT NULL")]
		public bool Ready
		{
			get
			{
				return this._Ready;
			}
			set
			{
				if ((this._Ready != value))
				{
					this._Ready = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Approve", DbType="Bit NOT NULL")]
		public bool Approve
		{
			get
			{
				return this._Approve;
			}
			set
			{
				if ((this._Approve != value))
				{
					this._Approve = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sort", DbType="Int NOT NULL")]
		public int Sort
		{
			get
			{
				return this._Sort;
			}
			set
			{
				if ((this._Sort != value))
				{
					this._Sort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatorId", DbType="BigInt NOT NULL")]
		public long OperatorId
		{
			get
			{
				return this._OperatorId;
			}
			set
			{
				if ((this._OperatorId != value))
				{
					this._OperatorId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JockeyId", DbType="BigInt NOT NULL")]
		public long JockeyId
		{
			get
			{
				return this._JockeyId;
			}
			set
			{
				if ((this._JockeyId != value))
				{
					this._JockeyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CutterId", DbType="Int NOT NULL")]
		public int CutterId
		{
			get
			{
				return this._CutterId;
			}
			set
			{
				if ((this._CutterId != value))
				{
					this._CutterId = value;
				}
			}
		}
	}
	
	public partial class sp_NewsToArchiveResult
	{
		
		private long _id;
		
		private string _Name;
		
		private long _ParentId;
		
		public sp_NewsToArchiveResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt NOT NULL")]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentId", DbType="BigInt NOT NULL")]
		public long ParentId
		{
			get
			{
				return this._ParentId;
			}
			set
			{
				if ((this._ParentId != value))
				{
					this._ParentId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
