<?xml version="1.0" encoding="utf-8"?><Database Name="NewsFactory" Class="NewsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost,1433;Initial Catalog=NewsFactory;User ID=NewsFactoryUser" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="NewsFactoryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Programs" Member="Programs">
    <Type Name="Program">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Director" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Rustv" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.News" Member="News">
    <Type Name="New">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="EditorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="NewsTime" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CalcTime" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TaskTime" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ProgramId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cassete" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Time_Code" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Duration" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Program_New" Member="Program" ThisKey="ProgramId" OtherKey="id" Type="Program" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vWeb_ProgramsFromCookie" Member="vWeb_ProgramsFromCookies">
    <Type Name="vWeb_ProgramsFromCookie">
      <Column Name="ProgramID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cookie" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CopyNews" Member="CopyNews">
    <Type Name="CopyNew">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="EditorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="NewsTime" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CalcTime" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TaskTime" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ProgramId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="GroupID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Cassete" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Time_Code" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Duration" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vUsersRights" Member="vUsersRights">
    <Type Name="vUsersRight">
      <Column Name="ProgramID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProgramName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="RightID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserPass" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="UserRate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tWeb_RssSources" Member="tWeb_RssSources">
    <Type Name="tWeb_RssSource">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vWeb_UsertForMessager" Member="vWeb_UsertForMessagers">
    <Type Name="vWeb_UsertForMessager">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vWeb_Users" Member="vWeb_Users">
    <Type Name="vWeb_User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vWeb_RssFeed" Member="vWeb_RssFeeds">
    <Type Name="vWeb_RssFeed">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="exsternalId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Lid" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SourceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Link" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ImgLink" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GUID" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Expr1" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vUsersProgramList" Member="vUsersProgramLists">
    <Type Name="vUsersProgramList">
      <Column Name="ProgramID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProgramName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="RightID" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="UserPass" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UserRate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.URoles" Member="URoles">
    <Type Name="URole">
      <Column Name="URoleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="URoleName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="URoleDescription" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="URoleProgDepend" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="URoleUndelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="URoleGroup" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.URightsToRole" Member="URightsToRoles">
    <Type Name="URightsToRole">
      <Column Name="URoleID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="URightID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="URole_URightsToRole" Member="URole" ThisKey="URoleID" OtherKey="URoleID" Type="URole" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="URight_URightsToRole" Member="URight" ThisKey="URightID" OtherKey="URightID" Type="URight" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.URights" Member="URights">
    <Type Name="URight">
      <Column Name="URightID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="URightName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="URightGroupName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="URightProgDepend" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="URightGroup" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="URightDescription" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="URightCh" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="pass" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Last_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ReadRate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PrintTemplateId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BlockTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AbrigeBlockTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OnlyMy" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Enter" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UUserToProgram" Member="UUserToPrograms">
    <Type Name="UUserToProgram">
      <Column Name="UUserToProgramID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProgramID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="URoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Program_UUserToProgram" Member="Program" ThisKey="ProgramID" OtherKey="id" Type="Program" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="URole_UUserToProgram" Member="URole" ThisKey="URoleID" OtherKey="URoleID" Type="URole" IsForeignKey="true" />
      <Association Name="User_UUserToProgram" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vBlocks" Member="vBlocks">
    <Type Name="vBlock">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="TypeName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BlockTime" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="TaskTime" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="CalcTime" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="NewsId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CreatorId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Ready" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Approve" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="JockeyId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CutterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.fWeb_GetUserIdFromCoockie" Method="fWeb_GetUserIdFromCoockie" IsComposable="true">
    <Parameter Name="Cookie" Parameter="cookie" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.fWeb_GetUserIdFromCoockie" Method="fWeb_GetUserIdFromCoockie1" IsComposable="true">
    <Parameter Name="Cookie" Parameter="cookie" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewsToCopybox" Method="sp_NewsToCopybox">
    <Parameter Name="News_id" Parameter="news_id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="GroupId" Parameter="groupId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewsFromCopyboxTemplate" Method="sp_NewsFromCopyboxTemplate">
    <Parameter Name="News_Id" Parameter="news_Id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="EditorId" Parameter="editorId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProgramId" Parameter="programId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.pWeb_NewNews" Method="pWeb_NewNews">
    <Parameter Name="programId" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.pWeb_ChekUserCookie" Method="pWeb_ChekUserCookie">
    <Parameter Name="Coockie" Parameter="coockie" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.fWeb_NewsWithBlocksToXML" Method="fWeb_NewsWithBlocksToXML" IsComposable="true">
    <Return Type="System.Xml.Linq.XElement" />
  </Function>
  <Function Name="dbo.fWeb_CheckUserRightForShowMessager" Method="fWeb_CheckUserRightForShowMessager" IsComposable="true">
    <Parameter Name="Userid" Parameter="userid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Boolean" />
  </Function>
  <Function Name="dbo.sp_NewsToArchive" Method="sp_NewsToArchive">
    <Parameter Name="News_id" Parameter="news_id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_NewsToArchiveResult">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ArchiveToNews" Method="sp_ArchiveToNews">
    <Parameter Name="id" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.pWeb_InsertRssToNews" Method="pWeb_InsertRssToNews">
    <Parameter Name="MessageId" Parameter="messageId" Type="System.Int32" DbType="Int" />
    <Parameter Name="NewsId" Parameter="newsId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="CreatorId" Parameter="creatorId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.pWeb_InsertRssFeed" Method="pWeb_InsertRssFeed">
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ImgLink" Parameter="imgLink" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Lid" Parameter="lid" Type="System.String" DbType="NText" />
    <Parameter Name="Link" Parameter="link" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Guid" Parameter="guid" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="SourceId" Parameter="sourceId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>