#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.cynegy
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="cynegy")]
	public partial class CynegyDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void Insertjob_subject(job_subject instance);
    partial void Updatejob_subject(job_subject instance);
    partial void Deletejob_subject(job_subject instance);
    partial void Insertnodes_ex3(nodes_ex3 instance);
    partial void Updatenodes_ex3(nodes_ex3 instance);
    partial void Deletenodes_ex3(nodes_ex3 instance);
    partial void Insertnodes_ex2(nodes_ex2 instance);
    partial void Updatenodes_ex2(nodes_ex2 instance);
    partial void Deletenodes_ex2(nodes_ex2 instance);
    partial void Insertnodes(nodes instance);
    partial void Updatenodes(nodes instance);
    partial void Deletenodes(nodes instance);
    partial void Insertnodes_ex1(nodes_ex1 instance);
    partial void Updatenodes_ex1(nodes_ex1 instance);
    partial void Deletenodes_ex1(nodes_ex1 instance);
    partial void Insertjob(job instance);
    partial void Updatejob(job instance);
    partial void Deletejob(job instance);
    #endregion
		
		public CynegyDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["cynegyConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CynegyDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CynegyDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CynegyDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CynegyDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<job_subject> job_subject
		{
			get
			{
				return this.GetTable<job_subject>();
			}
		}
		
		public System.Data.Linq.Table<nodes_ex3> nodes_ex3
		{
			get
			{
				return this.GetTable<nodes_ex3>();
			}
		}
		
		public System.Data.Linq.Table<nodes_ex2> nodes_ex2
		{
			get
			{
				return this.GetTable<nodes_ex2>();
			}
		}
		
		public System.Data.Linq.Table<nodes> nodes
		{
			get
			{
				return this.GetTable<nodes>();
			}
		}
		
		public System.Data.Linq.Table<nodes_ex1> nodes_ex1
		{
			get
			{
				return this.GetTable<nodes_ex1>();
			}
		}
		
		public System.Data.Linq.Table<job> job
		{
			get
			{
				return this.GetTable<job>();
			}
		}
		
		public System.Data.Linq.Table<v_files> v_files
		{
			get
			{
				return this.GetTable<v_files>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.job_subject")]
	public partial class job_subject : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _node_id;
		
		private System.Guid _job_node_id;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnode_idChanging(System.Guid value);
    partial void Onnode_idChanged();
    partial void Onjob_node_idChanging(System.Guid value);
    partial void Onjob_node_idChanged();
    #endregion
		
		public job_subject()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_node_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid node_id
		{
			get
			{
				return this._node_id;
			}
			set
			{
				if ((this._node_id != value))
				{
					this.Onnode_idChanging(value);
					this.SendPropertyChanging();
					this._node_id = value;
					this.SendPropertyChanged("node_id");
					this.Onnode_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_node_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid job_node_id
		{
			get
			{
				return this._job_node_id;
			}
			set
			{
				if ((this._job_node_id != value))
				{
					this.Onjob_node_idChanging(value);
					this.SendPropertyChanging();
					this._job_node_id = value;
					this.SendPropertyChanged("job_node_id");
					this.Onjob_node_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nodes_ex3")]
	public partial class nodes_ex3 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private int _deleted;
		
		private System.Guid _parent_id;
		
		private int _type;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OndeletedChanging(int value);
    partial void OndeletedChanged();
    partial void Onparent_idChanging(System.Guid value);
    partial void Onparent_idChanged();
    partial void OntypeChanging(int value);
    partial void OntypeChanged();
    #endregion
		
		public nodes_ex3()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="Int NOT NULL")]
		public int deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid parent_id
		{
			get
			{
				return this._parent_id;
			}
			set
			{
				if ((this._parent_id != value))
				{
					this.Onparent_idChanging(value);
					this.SendPropertyChanging();
					this._parent_id = value;
					this.SendPropertyChanged("parent_id");
					this.Onparent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int NOT NULL")]
		public int type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nodes_ex2")]
	public partial class nodes_ex2 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private long _order;
		
		private System.Guid _parent_id2;
		
		private int _type2;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnorderChanging(long value);
    partial void OnorderChanged();
    partial void Onparent_id2Changing(System.Guid value);
    partial void Onparent_id2Changed();
    partial void Ontype2Changing(int value);
    partial void Ontype2Changed();
    #endregion
		
		public nodes_ex2()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[order]", Storage="_order", DbType="BigInt NOT NULL")]
		public long order
		{
			get
			{
				return this._order;
			}
			set
			{
				if ((this._order != value))
				{
					this.OnorderChanging(value);
					this.SendPropertyChanging();
					this._order = value;
					this.SendPropertyChanged("order");
					this.OnorderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_id2", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid parent_id2
		{
			get
			{
				return this._parent_id2;
			}
			set
			{
				if ((this._parent_id2 != value))
				{
					this.Onparent_id2Changing(value);
					this.SendPropertyChanging();
					this._parent_id2 = value;
					this.SendPropertyChanged("parent_id2");
					this.Onparent_id2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type2", DbType="Int NOT NULL")]
		public int type2
		{
			get
			{
				return this._type2;
			}
			set
			{
				if ((this._type2 != value))
				{
					this.Ontype2Changing(value);
					this.SendPropertyChanging();
					this._type2 = value;
					this.SendPropertyChanged("type2");
					this.Ontype2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nodes")]
	public partial class nodes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private System.Guid _parent_id;
		
		private System.Nullable<System.Guid> _predecessor_id;
		
		private int _type;
		
		private System.DateTime _creation_date;
		
		private string _name;
		
		private int _children;
		
		private int _deleted_children;
		
		private System.Nullable<int> _sub_type;
		
		private System.Nullable<int> _creator_id;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void Onparent_idChanging(System.Guid value);
    partial void Onparent_idChanged();
    partial void Onpredecessor_idChanging(System.Nullable<System.Guid> value);
    partial void Onpredecessor_idChanged();
    partial void OntypeChanging(int value);
    partial void OntypeChanged();
    partial void Oncreation_dateChanging(System.DateTime value);
    partial void Oncreation_dateChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnchildrenChanging(int value);
    partial void OnchildrenChanged();
    partial void Ondeleted_childrenChanging(int value);
    partial void Ondeleted_childrenChanged();
    partial void Onsub_typeChanging(System.Nullable<int> value);
    partial void Onsub_typeChanged();
    partial void Oncreator_idChanging(System.Nullable<int> value);
    partial void Oncreator_idChanged();
    #endregion
		
		public nodes()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid parent_id
		{
			get
			{
				return this._parent_id;
			}
			set
			{
				if ((this._parent_id != value))
				{
					this.Onparent_idChanging(value);
					this.SendPropertyChanging();
					this._parent_id = value;
					this.SendPropertyChanged("parent_id");
					this.Onparent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_predecessor_id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> predecessor_id
		{
			get
			{
				return this._predecessor_id;
			}
			set
			{
				if ((this._predecessor_id != value))
				{
					this.Onpredecessor_idChanging(value);
					this.SendPropertyChanging();
					this._predecessor_id = value;
					this.SendPropertyChanged("predecessor_id");
					this.Onpredecessor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int NOT NULL")]
		public int type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creation_date", DbType="DateTime NOT NULL")]
		public System.DateTime creation_date
		{
			get
			{
				return this._creation_date;
			}
			set
			{
				if ((this._creation_date != value))
				{
					this.Oncreation_dateChanging(value);
					this.SendPropertyChanging();
					this._creation_date = value;
					this.SendPropertyChanged("creation_date");
					this.Oncreation_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_children", DbType="Int NOT NULL")]
		public int children
		{
			get
			{
				return this._children;
			}
			set
			{
				if ((this._children != value))
				{
					this.OnchildrenChanging(value);
					this.SendPropertyChanging();
					this._children = value;
					this.SendPropertyChanged("children");
					this.OnchildrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted_children", DbType="Int NOT NULL")]
		public int deleted_children
		{
			get
			{
				return this._deleted_children;
			}
			set
			{
				if ((this._deleted_children != value))
				{
					this.Ondeleted_childrenChanging(value);
					this.SendPropertyChanging();
					this._deleted_children = value;
					this.SendPropertyChanged("deleted_children");
					this.Ondeleted_childrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sub_type", DbType="Int")]
		public System.Nullable<int> sub_type
		{
			get
			{
				return this._sub_type;
			}
			set
			{
				if ((this._sub_type != value))
				{
					this.Onsub_typeChanging(value);
					this.SendPropertyChanging();
					this._sub_type = value;
					this.SendPropertyChanged("sub_type");
					this.Onsub_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creator_id", DbType="Int")]
		public System.Nullable<int> creator_id
		{
			get
			{
				return this._creator_id;
			}
			set
			{
				if ((this._creator_id != value))
				{
					this.Oncreator_idChanging(value);
					this.SendPropertyChanging();
					this._creator_id = value;
					this.SendPropertyChanged("creator_id");
					this.Oncreator_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nodes_ex1")]
	public partial class nodes_ex1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private System.Nullable<int> _modificator_id;
		
		private System.DateTime _modification_date;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void Onmodificator_idChanging(System.Nullable<int> value);
    partial void Onmodificator_idChanged();
    partial void Onmodification_dateChanging(System.DateTime value);
    partial void Onmodification_dateChanged();
    #endregion
		
		public nodes_ex1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modificator_id", DbType="Int")]
		public System.Nullable<int> modificator_id
		{
			get
			{
				return this._modificator_id;
			}
			set
			{
				if ((this._modificator_id != value))
				{
					this.Onmodificator_idChanging(value);
					this.SendPropertyChanging();
					this._modificator_id = value;
					this.SendPropertyChanged("modificator_id");
					this.Onmodificator_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modification_date", DbType="DateTime NOT NULL")]
		public System.DateTime modification_date
		{
			get
			{
				return this._modification_date;
			}
			set
			{
				if ((this._modification_date != value))
				{
					this.Onmodification_dateChanging(value);
					this.SendPropertyChanging();
					this._modification_date = value;
					this.SendPropertyChanged("modification_date");
					this.Onmodification_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.job")]
	public partial class job : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _job_status;
		
		private bool _job_disabled;
		
		private System.Guid _job_node_id;
		
		private int _job_type;
		
		private string _job_data;
		
		private string _additional_info;
		
		private int _percent;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onjob_statusChanging(System.Guid value);
    partial void Onjob_statusChanged();
    partial void Onjob_disabledChanging(bool value);
    partial void Onjob_disabledChanged();
    partial void Onjob_node_idChanging(System.Guid value);
    partial void Onjob_node_idChanged();
    partial void Onjob_typeChanging(int value);
    partial void Onjob_typeChanged();
    partial void Onjob_dataChanging(string value);
    partial void Onjob_dataChanged();
    partial void Onadditional_infoChanging(string value);
    partial void Onadditional_infoChanged();
    partial void OnpercentChanging(int value);
    partial void OnpercentChanged();
    #endregion
		
		public job()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_status", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid job_status
		{
			get
			{
				return this._job_status;
			}
			set
			{
				if ((this._job_status != value))
				{
					this.Onjob_statusChanging(value);
					this.SendPropertyChanging();
					this._job_status = value;
					this.SendPropertyChanged("job_status");
					this.Onjob_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_disabled", DbType="Bit NOT NULL")]
		public bool job_disabled
		{
			get
			{
				return this._job_disabled;
			}
			set
			{
				if ((this._job_disabled != value))
				{
					this.Onjob_disabledChanging(value);
					this.SendPropertyChanging();
					this._job_disabled = value;
					this.SendPropertyChanged("job_disabled");
					this.Onjob_disabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_node_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid job_node_id
		{
			get
			{
				return this._job_node_id;
			}
			set
			{
				if ((this._job_node_id != value))
				{
					this.Onjob_node_idChanging(value);
					this.SendPropertyChanging();
					this._job_node_id = value;
					this.SendPropertyChanged("job_node_id");
					this.Onjob_node_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_type", DbType="Int NOT NULL")]
		public int job_type
		{
			get
			{
				return this._job_type;
			}
			set
			{
				if ((this._job_type != value))
				{
					this.Onjob_typeChanging(value);
					this.SendPropertyChanging();
					this._job_type = value;
					this.SendPropertyChanged("job_type");
					this.Onjob_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_data", DbType="NVarChar(MAX)")]
		public string job_data
		{
			get
			{
				return this._job_data;
			}
			set
			{
				if ((this._job_data != value))
				{
					this.Onjob_dataChanging(value);
					this.SendPropertyChanging();
					this._job_data = value;
					this.SendPropertyChanged("job_data");
					this.Onjob_dataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_additional_info", DbType="NVarChar(MAX)")]
		public string additional_info
		{
			get
			{
				return this._additional_info;
			}
			set
			{
				if ((this._additional_info != value))
				{
					this.Onadditional_infoChanging(value);
					this.SendPropertyChanging();
					this._additional_info = value;
					this.SendPropertyChanged("additional_info");
					this.Onadditional_infoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[percent]", Storage="_percent", DbType="Int NOT NULL")]
		public int percent
		{
			get
			{
				return this._percent;
			}
			set
			{
				if ((this._percent != value))
				{
					this.OnpercentChanging(value);
					this.SendPropertyChanging();
					this._percent = value;
					this.SendPropertyChanged("percent");
					this.OnpercentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_files")]
	public partial class v_files
	{
		
		private System.Guid _node_id;
		
		private System.Guid _parent_id;
		
		private string _filename;
		
		private string _name;
		
		private string _filetype;
		
		public v_files()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_node_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid node_id
		{
			get
			{
				return this._node_id;
			}
			set
			{
				if ((this._node_id != value))
				{
					this._node_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid parent_id
		{
			get
			{
				return this._parent_id;
			}
			set
			{
				if ((this._parent_id != value))
				{
					this._parent_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filename", DbType="NVarChar(1024) NOT NULL", CanBeNull=false)]
		public string filename
		{
			get
			{
				return this._filename;
			}
			set
			{
				if ((this._filename != value))
				{
					this._filename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(1024) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filetype", DbType="NVarChar(24) NOT NULL", CanBeNull=false)]
		public string filetype
		{
			get
			{
				return this._filetype;
			}
			set
			{
				if ((this._filetype != value))
				{
					this._filetype = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
